### ISSUE TITLE
feedback wanted: do you care which version of the Rust compiler ripgrep targets?

### ISSUE THREAD

**Issue by BurntSushi** [BurntSushi/ripgrep#1019]
In this issue, I'm asking for feedback from any user, and I'm particularly interested in getting feedback from folks that maintain ripgrep in some package repository.

What I'd like to know is: do you care which version of the Rust compiler ripgrep targets, and if so, how does it impact you?

There are at least a couple different aspects to this question. For example:

* That we document a minimum Rust compiler version at all.
* That we support Rust compilers older than a few months.

My policy for this has been relatively ad hoc, but fairly conservative in the context of the Rust ecosystem.  I've mostly done this out of "good sense," in that it seems better for ripgrep to compile on more versions of the Rust compiler than not. However, what I'd like to know is whether it's worth doing this. For example, if ripgrep changed to "only guaranteed to compile on the latest stable release of the Rust compiler," how would that impact you?

What I'm trying to figure out here is what kind of room I have to maneuver. For example, sometime around the end of the year, Rust 2018 will be released, and ripgrep will eventually want to move to that. What I'd like to figure out is _when_ that kind of move would be acceptable, and in order to do that, I need to ask people how the minimum supported Rust version impacts them. So any kind of experience you can offer would be great!

cc @svenstaro @roblourens @dstcruz @joshtriplett @infinity0 @carlwgeorge @ignatenkobrain @cuviper @sylvestre

**Comment by ignatenkobrain** [comment]
In Fedora we will always keep latest compiler once it gets release. So "stick to the latest and coolest release"

**Comment by svenstaro** [comment]
In Arch we don't care about any compiler but the latest stable. :P

**Comment by tshepang** [comment]
Not to speak for Debian, but my guess is that whichever version of rustc is in Testing should be one that is supported, or one in Unstable at worst. Stable does not feature in this decision since the version of ripgrep there will not change, essentially.

**Comment by DoumanAsh** [comment]
As long as it targets latest stable I don't care

**Comment by sylvestre** [comment]
For debian and Ubuntu, last stable is fine.

For now, I don't think we will backport rg to debian stable.

**Comment by federicomenaquintero** [comment]
For openSUSE, we pick up the latest compiler version.

For SLE (Suse Linux Enterprise), we'll freeze the compiler at the version that the long-term Firefox release will require.  I believe FF60 needs rustc 1.26.2, so that's what we'll use in SLE.

(For librsvg, I'm trying to tie it to the same version that Firefox requires, so that they will both work in the enterprise distro.)

**Comment by cuviper** [comment]
Fedora's `rustc` is continuously updated, as mentioned, and I update EPEL7 this way too.  For RHEL proper, we're currently only shipping Rust in the Developer Tools `rust-toolset`, rebased quarterly.

**Comment by BurntSushi** [comment]
Thanks for the feedback so far! One of the things I'm interested in is figuring out the ramifications of tracking Rust stable instead of "Rust stable minus N" where N is somewhat loosely determined. I know some of you already mentioned that tracking Rust stable is fine, but for example, @federicomenaquintero, if ripgrep started tracking Rust stable, how would that impact you? Would you be able to just package last version of ripgrep that worked on the version of Rust that you're using?

**Comment by joshtriplett** [comment]
Generally speaking, if rustc isn't getting updated then neither will ripgrep. So you don't need to worry too much about the scenario where ripgrep gets updated but the update can't get packaged because rustc doesn't get updated.

The one case where that might cause a problem: if you ever need to put out an urgent bugfix for ripgrep (e.g. a hypothetical security issue parsing untrusted ignore files) then many other considerations for minimal updates and working on older rustc versions would apply.

**Comment by BurntSushi** [comment]
> The one case where that might cause a problem: if you ever need to put out an urgent bugfix for ripgrep (e.g. a hypothetical security issue parsing untrusted ignore files) then many other considerations for minimal updates and working on older rustc versions would apply.

Yeah that's a good one. I feel like if something like that were ever to happen, I'd just cut a branch at whatever version of ripgrep needs the fix and publish a patch release there. I don't really have the infrastructure in place to do it, and I'm not sure if I have the bandwidth to do it either, but I'd be willing to entertain the occasional backport if it's strongly motivated.

**Comment by cuviper** [comment]
> Generally speaking, if rustc isn't getting updated then neither will ripgrep.

That's true of the *packaged* ripgrep.  The remaining question is whether you want to support folks using their distro toolchain to `cargo install ripgrep` on their own.

**Comment by BurntSushi** [comment]
> That's true of the packaged ripgrep. The remaining question is whether you want to support folks using their distro toolchain to `cargo install ripgrep` on their own.

Yeah, it's becoming clear to me that this will be the key thing that is lost if ripgrep were to switch to "latest stable only" policy. I'm not sure how highly to weight this use case. :-/ I do know that users appreciate being able to `cargo install ripgrep`, but I also feel like those with `cargo` installed are _probably_ writing Rust code, and if they're writing Rust code, they're probably not an older Rust version or are even using `rustup`. But I'm of course waving my hands here!

**Comment by joshtriplett** [comment]
@cuviper I feel like, now that we have a much better story for how distributions can package software like ripgrep, and people *can* `apt install ripgrep` or equivalent in popular distributions (and other distributions have examples to follow to make that work), I'm a lot less worried about `cargo install ripgrep` building the latest ripgrep on old cargo/rustc. I *especially* don't think people should expect that to work on, say, Debian stable, or testing during a freeze.

I'd still like to see us add metadata to `Cargo.toml` for rustc/cargo dependencies so that we get an early, clear error message for that kind of thing. (And that would also help when generating build dependencies.) But that isn't ripgrep's problem.

**Comment by cuviper** [comment]
I do expect that most C and C++ software should be able to build with the system GCC, even on LTS-ish distros.  (Although I admit el7's gcc-4.8.5 is now old enough to be annoying, nevermind el6, but that's why we have devtoolset.) In the long term, I expect that Rust will settle down in a similar way.  For `ripgrep` in particular, it appears to be settling as a standard packaged distro tool too. 😄 

> I'd still like to see us add metadata to Cargo.toml for rustc/cargo dependencies so that we get an early, clear error message for that kind of thing.

Big 👍

**Comment by joshtriplett** [comment]
@cuviper C projects tend to adopt new C features more conservatively. But I've definitely found that "modern C++" software often doesn't build with LTS C++ compilers.

**Comment by Ameobea** [comment]
I'm usually nightly all the time, so as long as it doesn't break *every* new nightly release (looking at you clippy) I'm happy.

**Comment by dcarosone** [comment]
Nightly on anything where rustup works, and/or pkgsrc on smartos + netbsd

**Comment by BurntSushi** [comment]
All righty, based on the feedback I've got so far, I'm going to try switching to a **latest stable** policy for the next release. In detail, it will probably look like this:

* Every patch release will compile on the same version of the Rust compiler as the previous patch release.
* New minor version releases of ripgrep may require a Rust compiler as recent as the latest stable release.

I think this should satisfy most everyone who commented, and should also let us backport patches if that becomes necessary.

If this doesn't work out for some reason or another, we can revert to a more conservative policy, but the benefits of sticking the latest stable release are too big to not try this at all.

**Comment by roblourens** [comment]
That's right, I usually just update to the latest stable each time I build it.
