### ISSUE TITLE
Obvious match missing from results when using group: a(.*c) does not match abc

### ISSUE THREAD

**Issue by phiresky** [BurntSushi/ripgrep#1064]
#### What version of ripgrep are you using?

ripgrep 0.10.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

#### Bug

Example:

`echo abc | rg --debug 'a(.*c)'`

```
DEBUG|grep_regex::literal|grep-regex/src/literal.rs:110: required literal found: "ac"
DEBUG|globset|globset/src/lib.rs:429: built glob set; 0 literals, 0 basenames, 8 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 0 regexes
```

doesn't find any results. The following all work:

`echo ac | rg 'a(.*c)'`

`echo abc | rg 'a.*c'`

`echo abc | ag 'a(.*c)'`

`echo abc | grep 'a\(.*c\)'`

**Comment by lespea** [comment]
Interestingly enough this also fails: `echo abc | rg --debug 'a(?:.*c)'` but this works: `echo abc | rg --debug 'a(.*)c'`

**Comment by BurntSushi** [comment]
Ug. This looks like a bug in ripgrep's inner literal extractor. It thinks `ac` is a literal that must appear in every match, but this is obviously wrong. The regex engine prefix/suffix detection is correct:

```
[andrew@Cheetah ~]$ regex-debug prefixes 'a(.*c)'
Cut(a)
[andrew@Cheetah ~]$ regex-debug suffixes 'a(.*c)'
Cut(c)
```

I diagnosed this from the `--debug` output. Cutting out the irrelevant stuff, you can see the problem here:

```
[andrew@Cheetah ~]$ echo abc | rg 'a(.*c)' --debug
DEBUG|grep_regex::literal|grep-regex/src/literal.rs:110: required literal found: "ac"
[andrew@Cheetah ~]$ echo abc | rg 'a.*c' --debug
DEBUG|grep_regex::literal|grep-regex/src/literal.rs:110: required literal found: "a"
```

I would have thought this was a regression since I touched this code as part of libripgrep work, but 0.9.0 exhibits the same bug.

**Comment by phiresky** [comment]
checking out ripgrep 0.0.1 (with `regex = "0.1.75"`) has the same bug
