### ISSUE TITLE
[feature request] search text inside .docx  

### ISSUE THREAD

**Issue by WiliTest** [BurntSushi/ripgrep#1072]
MS word .docx are made to store text on windows. It would be great to be able to search inside these files.

Thanks for your great work! (But I'm still looking for an app that could do that)

**Comment by BurntSushi** [comment]
ripgrep is primarily a tool for searching plain text or otherwise UTF-8 encoded data. It is *not* a tool that knows how to decode and read arbitrary files. It will **never** be such a tool.

While ripgrep does have some support for understanding different types of files, such as compressed files, the support is limited and only intended as a low-effort-but-big-gain-in-many-cases kind of feature.

If you have a tool that can convert docx files to plain text, then you should be able to search them pretty easily by using the `--pre` flag.

**Comment by brileyd** [comment]
Is the some way to tell rg that a docx file is just a zip?  I attempted to use the -z option, but rg doesn't reconize docx as a zip.

**Comment by BurntSushi** [comment]
The `-z` flat only recognizes a fixed set of file extensions. You can either unzip the file yourself and search it, it use the `--pre` flag.
