### ISSUE TITLE
Is there a way to provide patterns for the path being searched?

### ISSUE THREAD

**Issue by jaepetto** [BurntSushi/ripgrep#1126]
#### What version of ripgrep are you using?

ripgrep 0.10.0 (rev 8a7db1a918)

#### How did you install ripgrep?

debian package

#### What operating system are you using ripgrep on?

Ubuntu 16.04

#### Describe your question, feature request, or bug.

Is there a way to provide patterns for the path being searched?

Typically, I am looking for HTML files that contain a specific pattern:
`sudo rg --no-ignore 'id="login" class="login-form"' /src`

The trick is that the `/src` folder contains code for multiple sites. Therefore, I'd like to use patterns in the path to search only in the folders I am interested in. It would be something around the lines of:
`/src/*client_a*` (using globbing) or `/src/.*client_a.*` (using regex).

**Comment by BurntSushi** [comment]
Please consider reading the documentation before filling issue requests. The guide specifically describes how to do this type of filtering: https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#manual-filtering-globs --- Although, you might just consider using standard shell globbing. For example, `rg foo src/*client_a*`.

**Comment by BurntSushi** [comment]
That's not a problem with ripgrep though. The shell is telling you the problem. That glob doesn't expand to any known path. Change your glob to a path that exists. For example, what is the output of `ls /src/*unibas*`?

**Comment by jaepetto** [comment]
I don't want to waste your time.

The `ls` command is indeed failing:
```
ls: cannot access '/src/*unibas*': No such file or directory
```

This is related to the fact that any `*unibas*` folder is not directly under `src`.

The aim is to look into all folders starting with `src` where the full path contains `unibas`.

**Comment by BurntSushi** [comment]
Yeah, this issue tracker is really more geared to ripgrep specific problems. If you need help figuring out how to use your shell's globbing facilities, you might have better luck with tutorials like this one: https://linuxhint.com/bash_globbing_tutorial/

As to your specific issue, if I were to take a stab in the dark, I'd say that if you have a `/home/jaepetto/foo/src` directory and you're searching from within `/home/jaepetto/foo`, then using `/src` doesn't make sense because `/src` is an absolute path. You instead probably want `ls ./src/*unibas*` where `./src` is a path relative to your current working directory.
