### ISSUE TITLE
Add `Candidate::from_utf8` to bypass `Path -> str` conversion?

### ISSUE THREAD

**Issue by quark-zju** [BurntSushi/ripgrep#1143]
In `globset`, patterns are `str` (as `Glob::new` takes a `str`), but paths to test are `Path` (as `GlobSet::is_match` takes a `Path`). It's a bit inconsistent.

There are 2 places where `Path` can be undesirable:
- Windows. Converting between `Path` and utf-8 `str` has a cost. In `globset`, that's `os_str_bytes`.
- Paths not generated from filesystem APIs. For example, source control software might store `path` in its internal form (ex. git tree objects or index), which might be utf-8 already. It can also be paths from a utf-8 `Makefile`, or some sort of source code.

It seems a `Candidate::from_utf8` API can be useful in this case.

If the idea sounds good, I can help draft a patch.

**Comment by BurntSushi** [comment]
> In `globset`, patterns are `str` (as `Glob::new` takes a `str`), but paths to test are `Path` (as `GlobSet::is_match` takes a `Path`). It's a bit inconsistent.

I don't agree. I don't think there is any inconsistency in a pattern having a different type than the thing it matches. The same is true for regexes themselves. Patterns are always `&str`, but they can match `&[u8]`.

> Windows. Converting between `Path` and utf-8 `str` has a cost. In `globset`, that's `os_str_bytes`.

Sorry, but I don't understand how your proposal resolves this. Could you please elaborate?

> Paths not generated from filesystem APIs. For example, source control software might store `path` in its internal form (ex. git tree objects or index), which might be utf-8 already. It can also be paths from a utf-8 `Makefile`, or some sort of source code.

Again, I don't understand how your proposal addresses this. If you have something that is known to be UTF-8, then you can convert it to a `&str` at zero cost using `unsafe`, at which point, you can build a `Path` at zero cost.

Overall, I don't think I understand what the intended semantics of this new `from_utf8` API should be, I don't understand what problem it's trying to solve and I don't understand how either of the two problems you've pointed out are addressed by your proposal. You might consider following up with a focus on the problem you're trying to solve and perhaps a couple of real examples.

**Comment by BurntSushi** [comment]
I see. More succinctly, I think what you're saying is that, today, since the API requires a `&Path`, there _may_ be a cost associated with converting that `&Path` internally to something that can be matched by the glob rules, and you would like a way to avoid that cost. In particular, you have a specific use case where you are storing paths somewhere that are already valid UTF-8, and can therefore be matched directly and shouldn't need any platform specific code to handle them.

In principle, I'd be OK with an addition to the API that lets you circumvent this. Note, however, that the internal representation of a `Candidate` isn't just the path, but it also contains path components such as `basename` and `ext`, which are used for optimization purposes. See here: https://github.com/BurntSushi/ripgrep/blob/118b950085ff674c1c7142bc5e171dd2b4688934/globset/src/lib.rs#L495-L496

Personally, I would rather like to see a benchmark on a real workload that benefits from a change like this.

**Comment by BurntSushi** [comment]
@quark-zju Could you please clarify whether this proposed new API would suit your use case?

```rust
    /// Create a new candidate for matching from the given path as a slice of
    /// arbitrary bytes.
    ///
    /// The purpose of using this method is that it may be able to circumvent
    /// some costly platform specific initialization steps.
    pub fn from_bytes<P: AsRef<[u8]> + ?Sized>(path: &'a P) -> Candidate<'a> {
        /// elided...
    }
```

If so, I'm not really convinced of this API. In particular, platform specific initialization steps are still required in order to handle path separators.

If you can:

1. Add this API.
2. Provide a convincing real world benchmark that shows a non-trivial improvement.

then I might be willing to reconsider this. Until then, I think this is just too complex and niche to justify. Yes, Windows requires a bit more processing here, but nothing is going to change that unless you can lobby Rust's standard library to expose an `OsStr`'s internal `WTF-8` representation, but thus far, they have remained ideologically opposed to such conveniences.
