### ISSUE TITLE
rg doesn't reset terminal color when interrupted

### ISSUE THREAD

**Issue by lambda** [BurntSushi/ripgrep#119]
I was grepping a large log file, and accidentally wrote a regex that matched a very large number of lines. After waiting for a minute of it just printing out lines to stdout, I killed `rg` with <kbd>Ctrl</kbd>-<kbd>C</kbd>. However, that left the `time` output and my shell prompt blue since apparently I'd interrupted it in the process of printing out a line number.

`rg` should probably catch SIGINT and reset the terminal color (or any other terminal changes) before exiting.

**Comment by BurntSushi** [comment]
Agreed.

Looks like we might be able to get away with the [`ctrlc`](https://github.com/Detegr/rust-ctrlc) crate.

**Comment by ticki** [comment]
Or simply go into raw mode and handle `C-c` manually. [termion](http://github.com/ticki/termion) allows this:

1. Enter raw mode.
2. Read from the TTY (`termion::get_tty`).
3. Handle `termion::event::Key::Ctrl('c')` manually.

**Comment by BurntSushi** [comment]
`termion` doesn't work on Windows, right? (Which I suppose isn't strictly a problem per se, I don't even know if this issue exists on Windows.)

In any case, it seems strictly better to handle `SIGTERM` instead of `C-c` manually, since `SIGTERM` can come from anywhere.

**Comment by andschwa** [comment]
@BurntSushi it's starting to exist on Windows with the additional support of ASCII color codes in new versions of ConHost shipped in Windows 10. (Oh god why do I know that?)

**Comment by BurntSushi** [comment]
Yeah I know, but that's too new to rely on IMO.

On Oct 18, 2016 14:47, "Andrew Schwartzmeyer" <notifications@github.com>
wrote:

@BurntSushi <https://github.com/BurntSushi> it's starting to exist on
Windows with the additional support of ASCII color codes in new versions of
ConHost shipped in Windows 10. (Oh god why do I know that?)

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/BurntSushi/ripgrep/issues/119#issuecomment-254602206>,
or mute the thread

**Comment by BurntSushi** [comment]
Yeah I know, but that's too new to rely on IMO.
