### ISSUE TITLE
Get the first X matches

### ISSUE THREAD

**Issue by nitrocode** [BurntSushi/ripgrep#1230]
#### What version of ripgrep are you using?

ripgrep 0.10.0

#### How did you install ripgrep?

brew instal ripgrep

#### What operating system are you using ripgrep on?

osx 10.14

#### Describe your question, feature request, or bug.

I'd like to get only the first X matches

**Comment by BurntSushi** [comment]
This has been requested for (not sure which issue) and I'm not going to add it. In part because "reporting the first match" is an ill-defined operation that may show the same thing each time even if the corpus remains fixed. Instead, you can extract the first match yourself fairly easily in a deterministic fashion: `rg foo --sort path | head -n1`.
