### ISSUE TITLE
couldn't install ripgrep with command "sudo apt-get install ripgrep" on ubuntu18.04

### ISSUE THREAD

**Issue by irreallich** [BurntSushi/ripgrep#1232]
log:

home-ubuntu:/etc/apt$ sudo apt-get install ripgrep
Reading package lists... Done
Building dependency tree       
Reading state information... Done

No apt package "ripgrep", but there is a snap with that name.
Try "snap install ripgrep"

E: Unable to locate package ripgrep
home-ubuntu:/etc/apt$ uname -a
Linux home-ubuntu 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
home-ubuntu:/etc/apt$

**Comment by BurntSushi** [comment]
That's because ripgrep isn't in Ubuntu 18.04, so I'm not sure why you're filing a bug report. The README says that `apt-get install ripgrep` only works for Ubuntu 18.10 or newer.

If you want to use ripgrep on an older Ubuntu, then use the snap if that's your thing. Or follow the instructions in the README and install the binary deb.

**Comment by dmdque** [comment]
What would it take to add ripgrep to Ubuntu 18.04?

**Comment by BurntSushi** [comment]
I don't know. My guess is that it isn't possible. This isn't the place to ask. I'm not an Ubuntu user and I don't know their packaging policies in detail.

**Comment by Ynjxsjmh** [comment]
1. Download the latest `.deb` package from the [release page](https://github.com/BurntSushi/ripgrep/releases)
2. Install it via:

```
sudo dpkg -i ripgrep_x.x.x_amd64.deb  # adapt version number and architecture
```
