### ISSUE TITLE
-j doesn't work for single large file.

### ISSUE THREAD

**Issue by leojay** [BurntSushi/ripgrep#1264]
#### What version of ripgrep are you using?

ripgrep 11.0.1 (rev 973de50c9e)
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

#### How did you install ripgrep?

I downloaded the binary from the github release page.

#### What operating system are you using ripgrep on?

Ubuntu 18.04

#### Describe your question, feature request, or bug.

I use rg to search a huge file (>20GB). And from "top" command, the cpu usage of rg is always <=100%, which means that rg is using only 1 core, instead of multiple cores.
"-j 1" and "-j 6" don't make any difference in terms of cpu usage and running time.
My workstation has 6c/12t cpu, 64GB of ram and nvme ssd. So I don't think the hardware is the restriction here. 

Does ripgrep support multithreading in single large file at all? If not, is it on the roadmap?

Thanks!
Leo

**Comment by BurntSushi** [comment]
> Does ripgrep support multithreading in single large file at all?

Nope.

> If not, is it on the roadmap?

Nope. It significantly complicates the implementation.

**Comment by roycewilliams** [comment]
Since this is a semi-FAQ item, and searches for this question lead to this issue... 

A viable "search a single very large file" workaround, external to ripgrep, is to use GNU Parallel with its `--pipepart -a [inputfile]` option. This will spawn multiple `rg` processes, and pass one raw *subsection* of `inputfile` to each process. You can adjust the number of blocks/processes to optimize for your hardware, including a `--block -1` option that spawns [core-count] processes to automaticallly divide the work into [core-count] chunks, so will use one process per core (which may then be bottlenecked on I/O).

(And for the record, I 100% support the idea that adding this to ripgrep would add complexity that @BurntSushi  is perfectly justified in avoiding! I'm hoping this workaround will help others, but if it's not a net win to drop this here, let me know and I will delete it)
