### ISSUE TITLE
Multiple issues configuring ripgrep

### ISSUE THREAD

**Issue by mcandre** [BurntSushi/ripgrep#1315]
#### What version of ripgrep are you using?

```console
$ rg --version
ripgrep 0.10.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
```

#### How did you install ripgrep?

apt-get

#### What operating system are you using ripgrep on?

Ubuntu 19.04 Disco Dingo

#### Describe your question, feature request, or bug.

* `$HOME/.ripgreprc` appears to be ignored on my machine.
* Configuration guide does not provide sufficient examples for excluding file and folder patterns from search results.
* Configuration guide is difficult to navigate to.

**Comment by BurntSushi** [comment]
> $HOME/.ripgreprc appears to be ignored on my machine

Consider reading the docs carefully. The existence of that file is insufficient: https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#configuration-file

> Configuration guide does not provide sufficient examples for excluding file and folder patterns from search results.

There are examples in the guide, so I don't know what you're talking about. See: https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#manual-filtering-globs

> Configuration guide is difficult to navigate to.

Again, I don't know what you're talking about.

I appreciate that you took the time to come an issue, but this is largely not actionable because you didn't really explain anything.
