### ISSUE TITLE
--count does not return 0

### ISSUE THREAD

**Issue by OJFord** [BurntSushi/ripgrep#1317]
#### What version of ripgrep are you using?

ripgrep 11.0.1
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

#### How did you install ripgrep?

brew

#### What operating system are you using ripgrep on?

Darwin 18.6.0

#### Describe your question, feature request, or bug.

```
$ rg --count 'this does not match anything' f
$
$ rg --count 'this does match something' f
1
$
```

For scripting purposes, I'd have preferred `0` than no output.

I thought I might have to accept that it's done in pursuit of compatibility, but:
```
$ grep --count 'this does not match anything' f
0
$
```

The exit code is 1 too, which is also a break from grep, and not desirable IMO, or maybe it's just because there really was a hard error, which is also what stopped any output?

**Comment by BurntSushi** [comment]
Interesting. I'm not sure this was intentional. Or at least, I can't think of any particular reason why I did this. However, if you run ripgrep over a _directly_ with the `--count` flag, then it will not print file paths with zero matches. grep does, but that divergence was intentional on my part because otherwise the output contains a lot of noise.

> The exit code is 1 too, which is also a break from grep, and not desirable IMO

An exit code of `1` for a non-match is correct and consistent with grep.

**Comment by OJFord** [comment]
> An exit code of 1 for a non-match is correct and consistent with grep.

Not when `--count` is supplied, it exits `0` and with stdout '0'.

**Comment by cebaa** [comment]
@BurntSushi Roger that, opened https://github.com/BurntSushi/ripgrep/issues/1370

**Comment by Backgammon-** [comment]
If I need to write shell arithmetic involving a count which can be zero (not that it matters, but I am counting connected external monitors), then the fact that ripgrep gives nothing instead of `0` is unnecessarily inconvenient and inconsistent, both with grep and with itself (imagine if `wc -l` printed nothing when run on an empty file...).

To preserve your intent re: noise: rather than diverging from grep by making zero counts print nothing, I think it would be better to give `0` when the count is actually zero, make `--count` over a directory omit empty counts by default, and add a flag to not omit empty counts when running over directories. This is slightly different from @cebaa's request, which just asks for the flag.

**Comment by BurntSushi** [comment]
This can be mitigated with the `--include-zero` flag, which was added in #1405 (commit https://github.com/BurntSushi/ripgrep/commit/a070722ff27c7d57d47b1766de9d253fbfe5bef9) and is available in ripgrep 12.
