### ISSUE TITLE
ripgrep git trees similar to git grep

### ISSUE THREAD

**Issue by dmitris** [BurntSushi/ripgrep#1459]
Possibly a silly question - would it be possible (or feasible) to extend ripgrep to be able to search in git trees (like other branches / commits) similar to how `git grep` does it?  I really like the tool, its speed, set of options etc. - but need to be able to search other branches / all commits (like https://github.com/dxa4481/truffleHog does).

**Comment by BurntSushi** [comment]
It's a neat idea, but I think it's definitively outside the scope of ripgrep. The addition flags required for such a rich feature alone would, I'm guessing, probably increase ripgrep's surface area by a significant amount. However, someone could use ripgrep's libraries to build a new command line tool dedicated to the purpose. That seems like a better approach to me.

**Comment by nyurik** [comment]
I ran into a similar issue - doing a global search for something, only to realize it was in an older branch (took me multiple hours!).  I honestly wish there was a way for `rg` to even just give an indication that the needed content is gziped (?) inside the git repo - so that I could start searching its content using other tools...
