### ISSUE TITLE
Add one default config path per platform

### ISSUE THREAD

**Issue by nu8** [BurntSushi/ripgrep#1668]
I am not a fan of the case-sensitive default, so I wanted to change the default
to case-insensitive (or smart-case), as I am tired of doing `rg -i something`.
So I look around, and I see this:

> ripgrep will not look in any predetermined directory for a config file
> automatically. Instead, you need to set the `RIPGREP_CONFIG_PATH` environment
> variable to the file path of your config file.

https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#configuration-file

I am disappointed by this, as it means that not only am I required to create a
file to get the default I want, but I also need to create an environment
variable. I use many programs, and I think that ripgrep is the first program I
have ever seen behave in this manner.

One might counter that different people are going to want to give different
names to the file, and maybe put it in different folders. Thats true, but I dont
think it would hurt to look in one folder. For example this pseudocode:

~~~php
if ($RIPGREP_CONFIG_PATH != '') {
   file_get_contents($RIPGREP_CONFIG_PATH);
} else if ($OS == 'Windows') {
   file_get_contents($USERPROFILE . '/ripgrep.rc');
} else {
   file_get_contents($HOME . '/ripgrep.rc');
}
~~~

This way people can utilize the default path. If they want a different path, or
if for some reason they are using a different OS, they can utilize the variable.

**Comment by BurntSushi** [comment]
Fixing your disappointment is not worth being the target of a righteous vocal minority that will crucify you for getting platform specific config file locations even slightly incorrect.

I've said in the past that if someone solves this problem well in a Rust crate that meets my standards, then I would be willing to consider it. But this has not happened yet to my knowledge.

Until then (perhaps indefinitely), set an environment variable. It should be trivial to do this in any environment.

**Comment by nu8** [comment]
Honestly man, algorithm wise this is a solved problem, and has been for many
years:

- https://github.com/golang/go/blob/18ea6f59/src/os/file.go#L492-L513
- https://github.com/php/php-src/blob/1c1165f8/ext/readline/readline_cli.c#L601-L605
- https://github.com/ruby/ruby/blob/1f09c436/win32/win32.c#L543-L596

but since Rust insisted on removing it (why?):

https://doc.rust-lang.org/std/env/fn.home_dir.html

If you dont want to write it, and a crate doesnt already exist, then I can write
one up if you are willing to consider it.

**Comment by BurntSushi** [comment]
Simply getting the home directory doesn't even come close to solving the problem. Sorry. I don't have the time to spec out the problem space for you, but "honestly man," it is a lot more complicated than you are portraying. It is full of platform specific details.

See also: https://github.com/BurntSushi/ripgrep/issues/196#issuecomment-362871536

**Comment by nu8** [comment]
Its hard to convey tone over the internet, but I get the sense you are angry or
annoyed with my line of comments. If I was rude, I apologize. I know that is a
non-apology apology, but in this case I think its warranted, as I honestly am
not trying to sling insults or anything like that. I am simply trying to present
the case, then if I still fail, I can say I tried.

So I am going to continue on, and if my comments both you just know that I am
trying to present a logical argument, not troll or anything like that.

To that end I would say this. When I say its a solved problem, its more like its
an unsolved problem. That because there probably and a specified standard
across every platform, only conventions. That is probably why you are concerned
with putting a single directory, as no one agrees on what that directory would
be, so you are worried regardless what you pick, people will say its the wrong
one.

But not making a choice can be bad too. By not making a choice, you force people
to create a file and environment variable. If you just make a choice, yes it
will be wrong in some opinion, but in other it will be right. And you can just
says "look, since no standard exists for this thing, I choose X. If that dont
suit you then use environemnt variable". Look at this, its even existed since
2005:

https://github.com/php/php-src/commit/16235379

if you want to abstain from making a choice, of course you can do that. Its your
code. But take for example this command:

~~~
git clone git://github.com/BurntSushi/ripgrep
~~~

hidden in this command is a bunch of answer to questions:

1. what local directory do I use?
2. do I create directory if not exist?
3. what branch do I use?
4. how many commit deep?

all those question have a default, as sometimes people realize that defaults
have value. Again I dont mean any hard feeling, I appreciate the great tool you
have created. Or I will say tools, because I appreciate the work you do on other
stuff too like the Regex crate.

**Comment by BurntSushi** [comment]
Thanks. Yes, this is a sore topic for me. Because people continually underestimate the difficulty and complexity involved in this. Even after I told you how hard it was, you just kind of shrugged it off and pointed me to functions that get the home directory of a user, but that isn't the hard part. Not even close. Even just describing the complexity of loading configuration files takes time, because the process for it is very different across Linux, macOS and Windows. (And even _that_ is a controversial statement, because some people would prefer that Linux and macOS use the same process!)

> all those question have a default, as sometimes people realize that defaults have value.

I mean, I created ripgrep. It and its ancestors (ack and ag) are perhaps one of the most obvious examples that _defaults matter_. So this argument doesn't really need to be made. The point is whether setting a default in this case is worth the benefits. I don't need to be convinced that defaults have benefits in the first place.

Given that you suggested dropping a config file into a user's `$HOME` directory, my guess is that you just simply aren't aware of the vociferousness of people who absolutely hate this. As a practical matter, I do not want to be the target of their zeal. Similarly, building out the infrastructure to get platform specific configuration file placement correct is just not something that I'm willing to spend my free time on. Somebody else has to do it. Some folks have, to varying levels of success. The [`directories`](https://github.com/dirs-dev/directories-rs) crate is probably the best example, but I won't use it. (Partially due to a couple technical reasons, but primarily due to non-technical ones and I won't discuss those publicly.) With that said, I'd encourage you to examine the implementation of that crate to get an idea of just how complex the task is.

> "look, since no standard exists for this thing, I choose X. If that dont suit you then use environment variable"

This ignores the costs of having both an environment variable and support for platform specific config directories, and the complexity of maintaining both instead of one.

> Look at this, its even existed since 2005:
>
> php/php-src@1623537#diff-43cd40d427070a1355f39a283ae22ac7R1187

I don't know what you're trying to show me with this link. Like, do you think I'm unaware that many tools plop config files into a user's home directory? I don't need to be shown that.

There are a few final points remaining:

* As a matter of subjective value judgment, I personally think you are _greatly_ overstating the annoyance of setting an environment variable. I admit it is a cost over having a default location to search for, but it is a teeny cost and avoids 1) attracting the zeal of Internet mobs that never stop whining about improper placement of config files and 2) avoids the implementation complexity of getting it correct.
* An environment variable has benefits. For example, if you know that `RIPGREP_CONFIG_PATH` isn't set, then you also know that ripgrep will never read anything from any configuration file. Similarly, if you need to know the location of ripgrep's config file, then all you need to do is consult `RIPGREP_CONFIG_PATH`. There's no need to go searching for the config file across various directories (depending on platform).
* A configuration file is not the only way to configure ripgrep. Aliases, functions or wrapper scripts are other fine ways to do it. AIUI, this is difficult to do correctly on Windows, and this was one of the primary reasons why configuration files were added in the first place. Otherwise, I probably would have insisted on folks using some other mechanism.

**Comment by BurntSushi** [comment]
> Its hard to convey tone over the internet, but I get the sense you are angry or
> annoyed with my line of comments. If I was rude, I apologize. I know that is a
> non-apology apology, but in this case I think its warranted, as I honestly am
> not trying to sling insults or anything like that. I am simply trying to present
> the case, then if I still fail, I can say I tried.

I appreciate you saying this. I'm not angry and I don't think you were rude, but yes, I am annoyed. This issue is a good example of someone posing a solution to a problem and not appreciating that there may be underlying complexities to it. It's similar to people saying, "why don't you _just_ do [something that seems simple but is actually really hard and complete with a bunch of trade offs that can be hard to see without a more thorough understanding of the problem domain]." Dealing with this as a maintainer of a free and open source project is emotionally difficult for me at least.

**Comment by nu8** [comment]
I get that people dont like stuff dumped in their HOME directory, but this isnt
that. The solution I image would be something like this pseudocode:

~~~php
$s = getenv('RIPGREP_CONFIG_PATH');
if (is_file($s)) {
   file_get_contents($s);
}
~~~

So you can see, its not really "dumping" anything anywhere. Not into the HOME
directory or anywhere else. Now if Ripgrep had a default, and if that default
existed, then Ripgrep would read it. But Ripgrep wouldnt actually be creating
any files.

At any rate, you are right, supporting what I am suggesting would be a
maintenance burden, if only a small one. So I respect if you do not wish to
support that. Thank you!

**Comment by BurntSushi** [comment]
>  if only a small one

No, it _wouldn't_ be a small one. That's my point.

No, ripgrep would not have to create any files. I never said that. What matters is _where ripgrep expects the files to be_. The code from your original post, for example, was `file_get_contents($HOME . '/ripgrep.rc');`. That means someone either has to set an env var or "dump" the config file into their home directory. The latter is an old but no longer "correct" convention. Instead, on Unix, you need to follow the XDG specification. In the common case, this means the config file would need to be put at `~/.config/ripgrep/config`, but there are a whole bunch of rules and various other environment variables that need to be respected to do it correctly. And that's just Unix. Windows has its own host of rules. As does macOS.

**Comment by nu8** [comment]
> Instead, on Unix, you need to follow the XDG specification. In
> the common case, this means the config file would need to be put at
> `~/.config/ripgrep/config`, but there are a whole bunch of rules and various
> other environment variables that need to be respected to do it correctly. And
> that's just Unix.

Youve made it clear that this whole topic is a sore subject, so I will try to
choose my words carefully. Youve also made a point that many people (perhaps me
included) dont understand the full complexity of this problem.

Well, maybe that true, but some other details should be mentioned. As I alluded
to in previous comment, I dont think an agreed upon standard existing for any
platform, only conventions. A good example of this is the XDG spec. Personally
I think following it would be a good idea, but I wouldnt fault programs that
wish to do something different. It should be noted, that XDG is neither defined
in the POSIX standard:

https://pubs.opengroup.org/onlinepubs/9699919799/download/index.html

Nor in the Linux kernel:

https://github.com/torvalds/linux/search?q=xdg

**Comment by BurntSushi** [comment]
> but I wouldnt fault programs that
> wish to do something different

_You_ might not. I myself don't care either. But many people do care and they are a vocal bunch that complain about it constantly. The only way to avoid that is to opt out of handling this at all (which is what I've done) or implement something that appeases the vocal bunch that care. I've said this over and over again. I don't know why I have to keep repeating it. :-/

**Comment by nu8** [comment]
I think at this time all the arguments have been made. Sorry again for dragging
this up, but I think some new good points were mentioned on both sides, and that
has value. I did search for this issue before posting, and from what I found I
didnt feel that all the points had been enumerated.

So if nothing else you can point people here as to why this hasnt been done and
wont be done. Thanks again.

**Comment by BurntSushi** [comment]
OK, fair enough, thanks.
