### ISSUE TITLE
--smart-case breaks Unicode range search

### ISSUE THREAD

**Issue by nu8** [BurntSushi/ripgrep#1708]
If I do a search like this:

~~~sh
rg '[\u07FF-\U0010FFFF]'
~~~

it works fine. But if I do this:

~~~sh
rg --smart-case '[\u07FF-\U0010FFFF]'
~~~

it fails. I dont actually do the above, but I do have a file:

~~~
C:\Users\Steven\ripgrep.txt
~~~

and this:

~~~
$env:RIPGREP_CONFIG_PATH = 'C:\Users\Steven\ripgrep.txt'
~~~

Is this expected result? If so what is the best way to handle this situation? I
dont want to delete my config file just to do certain searches.

**Comment by BurntSushi** [comment]
Why did you delete the issue template? Please fill it out. Your issue is missing at least a few essential pieces of information that the issue template for reporting a bug requests.

Any please share your config file.

In the future, when filing bugs on _any_ project, please consider providing more detail than "it breaks" or "doesn't work." That doesn't mean anything to me. That's why the issue template exists. I don't understand why people ignore it.

**Comment by nu8** [comment]
@BurntSushi I mean, all you have to do, it literally try the example I gave,
with any other variables not making a difference. But if you insist:

~~~
PS D:\Desktop> rg --version
ripgrep 12.1.1 (rev 7cb211378a)
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
~~~

> How did you install ripgrep?

https://github.com/BurntSushi/ripgrep/releases/download/12.1.1/ripgrep-12.1.1-x86_64-pc-windows-msvc.zip

Here is example of some lines that are matching in error:

~~~
autumn\config.yaml
3:disableKinds:
7:markup:
8:   goldmark:
10:         linkify: false
~~~

**Comment by BurntSushi** [comment]
Please fill out the complete issue template. I'm not going to spend my time trying to guess what you're saying.

**Comment by nu8** [comment]
Jesus Christ dude, what is your deal? I have given more than enough information
to reproduce the issue. Youve clearly not even attempted to reproduce it, else
you wouldve said something along the lines of "works for me". Here:

#### What version of ripgrep are you using?

~~~
ripgrep 12.1.1 (rev 7cb211378a)
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
~~~

#### How did you install ripgrep?

1. download this https://github.com/BurntSushi/ripgrep/releases/download/12.1.1/ripgrep-12.1.1-x86_64-pc-windows-msvc.zip
2. extract

#### What operating system are you using ripgrep on?

~~~
Microsoft Windows [Version 10.0.18363.1082]
~~~

#### Describe your bug.

RipGrep matches characters outside of the range given.

#### What are the steps to reproduce the behavior?

~~~
rg --smart-case '[\u07FF-\U0010FFFF]'
~~~

Example file:

~~~
disableKinds:
markup:
   goldmark:
         linkify: false
~~~

#### What is the actual behavior?

All the lines in example file match in error.

#### What is the expected behavior?

Lines should only match if they are in the given range.

**Comment by nu8** [comment]
Looks to be the same errant behavior all the way back to 11.0.0. As a
workaround, I will keep my config file and use this:

~~~
rg -s '[\u07FF-\U0010FFFF]'
~~~

**Comment by BurntSushi** [comment]
I'm glad you edited your comment, because I don't appreciate the hostility. I was on mobile when I was responding to you earlier, so no, I didn't have a chance to try anything. I always try to triage issues when I can, so that when I do sit down to look more closely, I have all the information I need. And I note that even after repeated requests to fill out the template, you still didn't quite do it completely. You left out the `--debug` output, and you didn't really explain why you thought the output was incorrect, which turned out to be important in this case.

Sometimes, bugs elude simple reproductions. But not in this case. It is extremely frustrating when I've gone through the trouble to setup bug reporters for success by asking for information that leads to a reproduction, only to have the reporter completely ignore it. I'm doing this in my spare time, and if every reporter was as difficult as you, I'd be spending a lot more time dealing with issues than I would like.

As for the issue you've reported, the output you're seeing is correct. I don't know whether your environment has colors enabled, but in mine, it's pretty clear what ripgrep is matching here:

![ripgrep-1708-smart-case-match](https://user-images.githubusercontent.com/456674/96355013-3b94ed80-10ab-11eb-8266-f46874520c01.png)

As you can see, ripgrep is matching a `k` in each line of the file, which is correct, because `k` is a lowercase character of `U+212A`, or `K`, which is the Kelvin sign and not `U+004B`, which is the latin uppercase letter `K`.

Perhaps though, you're wondering why smart case is even applying here. That's because smart case applies when two conditions are met: there is at least one literal character in the pattern _and_ none of the _literals_ in the pattern are considered uppercase with respect to Unicode. In your pattern, you have literals (two of them, `\u07FF` and `\U0010FFFF`) _and_ neither of those literals are uppercase according to Unicode:

```
$ printf '\xDF\xBF' | rg '\p{Uppercase}'
$ printf '\xF4\x8F\xBF\xBF' | rg '\p{Uppercase}'
$
```

Thus, smart case kicks in and enables case insensitive search. Since `U+212A` is in the range `U+07FF-U+0010FFFF`, the case folded range includes `U+006B`, which is the lowercase latin letter `k`.

You're proposed work-around is the simplest way to avoid the issue. Another possible way would be to disable Unicode case folding and just use ASCII case folding, but ripgrep exposes no way to do that while simultaneously using other Unicode features (in this case, the `\u` syntax).

I've updated the docs of `--smart-case` to lay out these rules more explicitly so that this is clearer in the future. Incidentally, this is one of the many reasons why ripgrep does not enable smart case by default.

**Comment by nu8** [comment]
> I'm glad you edited your comment, because I don't appreciate the hostility.

I was (and am) pretty upset by your previous behavior. I am going to try to give
some context on why that is the case.

I am not your average user. I make [thousands of commits][1] a year, across a
number of repos. As well as create [weekly or sometimes daily][2] issues to
repositories across GitHub. I am a [trusted user][3] on Stack Overflow, with
over 1,000 answers, and hundreds of questions. I know how to post issues. I
know how to do [an MCVE][4].

[1]://github.com/nu8
[2]://github.com/search?type=issues&q=author:nu8
[3]://stackoverflow.com/users/1002260
[4]://stackoverflow.com/help/minimal-reproducible-example

When I post an issue, I take the time to post it right. Even if that means
taking hours to get something reproducible. Even now, I am taking the time to
download multiple Windows 10 ISOs, each about 4 GB, just so I can load those
into VirtualBox to test a C++ Unicode issue. So when I post an issue, I make
sure that (at least to myself) it is complete.

So when someone comes back and says: "sorry, I can help you, you didnt fill out
form ABC", I dont accept that. The goal of a boilerplate form is to get all the
information needed to solve the problem, or to at least be able to reproduce it.
I did that. From even the original post, I had all the information needed to
reproduce this. If you ran my command on a file with even a single lowercase
`k`, then boom, issue reproduced. So unless you tested my command on a file
without a lowercase `k` (not likely), then the form was pointless.

I get your position. You dont want a bunch of low-effort posts saying "Guhh
RipGrep dont work". This wasnt that. The icing on the cake was that with all
your bluster, you clearly hadnt even tried to repro. Mentally you were refusing
until I did things "your way".

> was on mobile when I was responding to you earlier, so no, I didn't have a
> chance to try anything. I always try to triage issues when I can, so that
> when I do sit down to look more closely, I have all the information I need.

Heres the thing. Thats your timetable. If you had ignored my issue, then come
back literally a month from now (November 17) when you had more time and then
responded, I would have been totally fine with it. I know people are busy. I
didnt need a response back in 8 minutes (which is what is actually was). I would
rather wait and let you get home, or even days later when you have more free
time and can sit down, then an argumentative response from a cell phone where
youre not even in a postition to test the issue.

> Sometimes, bugs elude simple reproductions. But not in this case.

Exactly. Thats why this was so frustrating to me. If you had tested the issue,
and couldnt reproduce, AND my original post was crap, then you would have every
right to be upset and demand proper form filling. But you didnt even take the
time to try to repro before starting the demands.

> As you can see, ripgrep is matching a `k` in each line of the file, which is
> correct, because `k` is a lowercase character of `U+212A`, or `K`, which is
> the Kelvin sign and not `U+004B`, which is the latin uppercase letter `K`.

This is matter of opinion, but I dont think any ASCII should be case matching
anything in the multibyte Unicode range. I dont think thats a good default. But
Im sure you have your own opinion on the matter, and also even if you agree
with me, it might not be simple to implement.

**Comment by BurntSushi** [comment]
> When I post an issue, I take the time to post it right.

Then fill out the issue template that the maintainer of the project has requested, please. It's not some bureaucratic nonsense. It's to help streamline the identification of bugs. The exact formatting isn't necessary (although it is helpful), but the information in it is, and your initial issue didn't have it. I didn't know what you were searching or why you thought it was wrong or what you were seeing.

Your other open source work looks wonderful, but that doesn't really matter here. When someone files a bug, unless I have a previous report with them, they're a mystery to me. I don't know their background, their context, what they do or don't know. That's the whole point of the issue template. To eliminate assumptions and provide the detail necessary to understand and fix a bug. It's to eliminate me having to _guess_ what people mean. Instead, people should _show_ what they mean. That's the point of the questions in the template.

> If you ran my command on a file with even a single lowercase
k, then boom, issue reproduced.

No, it wouldn't. All you said was that it didn't work. I don't know what that means.

> but I dont think any ASCII should be case matching
anything in the multibyte Unicode range

You'll have to take that up with Unicode. Probably the "most correct" answer is locale support with specialized tailoring, but ripgrep doesn't and likely will never have it.
