### ISSUE TITLE
support default config paths when RIPGREP_CONFIG_PATH isn't set

### ISSUE THREAD

**Issue by mvdan** [BurntSushi/ripgrep#1719]
This is an extension of https://github.com/BurntSushi/ripgrep/pull/772. It reads:

> This does not add any support for auto-loading config files from pre-determined locations like one's `$XDG_CONFIG_HOME` directory. [It was decided](https://github.com/BurntSushi/ripgrep/issues/196#issuecomment-362850321) to punt on that for now, and one wonders how far we can get with just the env var approach!

It seems like the main reason was because Rust didn't have good software to do the right thing on all platforms in a nice way. It's been nearly three years, so I hope that situation has changed :) 

I think this could be solved without going into project-specific or PWD-relative config files. Those use cases can continue to use explicit env vars like before, for now.

My personal use case is not needing to pollute my global environment to have a global ripgrep config file. Pretty much every other tool I use already knows to look in `~/.config/<name>/somefile` by default, and I think it's reasonable to expect the same here. Another advantage would be to create a standard for where such a config file should be, making "dotfiles" repos more consistent with their ripgrep config locations.

**Comment by mvdan** [comment]
I certainly won't delete this thread :) I did try to search for previous incarnations but found none.

> My environment is littered with oodles of variables. And even so, I don't think it's a problem worth solving.

I think that's up to personal preference, but I see not being forced to litter one's global environment akin to not being forced to litter one's home directory with "dot files". This is the same reasosn why many tools are being lobbied to accept `~/.config/foo` as well as `~/.foo`.

> That's a good one, but `RIPGREP_CONFIG_PATH` would (probably) never go away for backwards compatibility reasons even if ripgrep started supporting XDG. So I guess I'd file this under "unfortunate."

You'd keep backwards compatibility for sure, but I also imagine that the vast majority of users would gradually switch to the default location. That seems like the best of both worlds to me :)

**Comment by mvdan** [comment]
As an aside, I'm very surprised that an external user can delete their thread and, by extension, delete the repo owner's comments as well. This seems like bad design. At most, they should be able to delete their own comments, but not take the entire thread down with them. Only the admins should be able to take that nuclear option.

**Comment by mvdan** [comment]
> the user who opened that issue deleted it

Hm, actually, I can't find any delete button in this issue, for example. Maybe it was a report that resulted in a deletion by GitHub staff. Have you reached out to them?

**Comment by egonelbre** [comment]
> Personally, I am not sympathetic to this. My environment is littered with oodles of variables. And even so, I don't think it's a problem worth solving. That is, I don't perceive this as a real problem that many users experience.

Unfortunately this is a problem on Windows where you are limited to 32K bytes of environment variables. And I've hit that limit a few times. Although, I doubt this being a problem for most people.

**Comment by thepudds** [comment]
Hi @BurntSushi, at least part of the 1668 conversation is in the google cache of the gitmemory site:

https://webcache.googleusercontent.com/search?q=cache:tzcRYmo7rH4J:https://gitmemory.com/issue/BurntSushi/ripgrep/1668/682573882+&cd=1&hl=en&ct=clnk&gl=us&client=safari

**Comment by thepudds** [comment]
Here is a comment from @BurntSushi from there:

_________

Thanks. Yes, this is a sore topic for me. Because people continually underestimate the difficulty and complexity involved in this. Even after I told you how hard it was, you just kind of shrugged it off and pointed me to functions that get the home directory of a user, but that isn't the hard part. Not even close. Even just describing the complexity of loading configuration files takes time, because the process for it is very different across Linux, macOS and Windows. (And even that is a controversial statement, because some people would prefer that Linux and macOS use the same process!)

> all those question have a default, as sometimes people realize that defaults have value.

I mean, I created ripgrep. It and its ancestors (ack and ag) are perhaps one of the most obvious examples that defaults matter. So this argument doesn't really need to be made. The point is whether setting a default in this case is worth the benefits. I don't need to be convinced that defaults have benefits in the first place.

Given that you suggested dropping a config file into a user's $HOME directory, my guess is that you just simply aren't aware of the vociferousness of people who absolutely hate this. As a practical matter, I do not want to be the target of their zeal. Similarly, building out the infrastructure to get platform specific configuration file placement correct is just not something that I'm willing to spend my free time on. Somebody else has to do it. Some folks have, to varying levels of success. The directories crate is probably the best example, but I won't use it. (Partially due to a couple technical reasons, but primarily due to non-technical ones and I won't discuss those publicly.) With that said, I'd encourage you to examine the implementation of that crate to get an idea of just how complex the task is.

> "look, since no standard exists for this thing, I choose X. If that dont suit you then use environment variable"

This ignores the costs of having both an environment variable and support for platform specific config directories, and the complexity of maintaining both instead of one.

> Look at this, its even existed since 2005:
php/php-src@1623537#diff-43cd40d427070a1355f39a283ae22ac7R1187

I don't know what you're trying to show me with this link. Like, do you think I'm unaware that many tools plop config files into a user's home directory? I don't need to be shown that.

There are a few final points remaining:
* As a matter of subjective value judgment, I personally think you are greatly overstating the annoyance of setting an environment variable. I admit it is a cost over having a default location to search for, but it is a teeny cost and avoids 1) attracting the zeal of Internet mobs that never stop whining about improper placement of config files and 2) avoids the implementation complexity of getting it correct.
* An environment variable has benefits. For example, if you know that RIPGREP_CONFIG_PATH isn't set, then you also know that ripgrep will never read anything from any configuration file. Similarly, if you need to know the location of ripgrep's config file, then all you need to do is consult RIPGREP_CONFIG_PATH. There's no need to go searching for the config file across various directories (depending on platform).
* A configuration file is not the only way to configure ripgrep. Aliases, functions or wrapper scripts are other fine ways to do it. AIUI, this is difficult to do correctly on Windows, and this was one of the primary reasons why configuration files were added in the first place. Otherwise, I probably would have insisted on folks using some other mechanism.

**Comment by BurntSushi** [comment]
@thepudds Thanks! I guess reading that, not all of it is directly relevant to this issue. There were some peculiarities with the previous issue that I was addressing that don't really apply to this one.

I think this issue comes down to whether it's worth adding support for default platform specific configuration files. One of the problems that I've said historically is that there aren't any crates yet that solve that problem to my satisfaction (which is still true, AFAIK). But even if there were, I'm not really convinced that setting an environment variable is enough of a problem to be worth adding this. [Setting random env vars is a common practice](https://github.com/BurntSushi/dotfiles/blob/master/.envrc) I think, and I don't really buy the comparison with littering one's `$HOME` directory with dotfiles. It's common to list the contents of one's home directory, but less common to list the entire environment and read each variable. On my system, `env | wc -l` outputs `63`, which is quite big. And many of them aren't even variables that I've explicitly set (e.g., `SSH_AUTH_SOCK`). But then again, I'm not bothered by dotfiles littered in my `$HOME` directory anyway.

**Comment by jacobisaliveandwell** [comment]
It's hard to look at the mountain of work that was done to make ripgrep possible and think that config files are too challenging. Considering the number of config related issues created and the hours you've poured into replying ~and considering~ to them, this seems to come down to a simple choice to not see the value others see and have explained for years.

For those focused on the code, I don't touch rust, but a quick search shows a few options. e.g. https://github.com/cjbassi/platform-dirs-rs

**Comment by BurntSushi** [comment]
> and think that config files are too challenging. 

ripgrep has support for config files.

> into replying ~and considering~ to them

I consider this to be a comment made in bad faith. If you do it again, you won't be welcome here.



> this seems to come down to a simple choice to not see the value others see and have explained for years.

This also feels like bad faith to me. I understand the value of platform specific default configuration directories. I even addressed it in my comments above. I just don't think they provide enough value over setting an environment variable.

I personally am getting pretty close to banning all discussion of config file location from this tracker. I initially believed that delegating the decision to an environment variable would be enough to satiate users: it's simple to understand and implement, permits putting the config file anywhere and you generally don't see folks complaining about setting env vars. Most of us probably have a lot set and an established mechanism to do so, regardless of platform. But lately, I've received a number of forceful and frustrating comments from users seemingly complaining that this isn't good enough. I have yet to see any compelling reason to reverse course. For that reason, I'm closing this issue.

**Comment by mvdan** [comment]
Thanks for the patience, @BurntSushi. I of course was not aware of the previous deleted thread when I opened this one. I sympathize with the struggle of having to say "no" to features in large open source projects and getting reactions because of that.

> I have yet to see any compelling reason to reverse course.

At least from my point of view, it's just "it would be nice to not clutter my global environment with an extra variable". Though I get that that's not a big deal and, ultimately, a subjective choice. It's not a hard-coded limitation, after all.

**Comment by lunaynx** [comment]
Sorry for the necropost, but this is still relevant today.

With all due respect, personally I don't have a problem with adding another environment variable to my shell config per se, I'll gladly do it. I simply object to the principle that this added friction is an intended part of the user experience in the first place, especially when ripgrep is quite literally the *only* piece of software I can think of that I use that behaves this way. I don't know what the crate situation was like back in the day, and I respect not wanting to deal with rolling your own implementation or maintaining your own crate for that, although there were already long established standards that are *not* simply littering the user's home directory (personally, I would value it even looking for a `~/.ripgreprc` by default over *nothing*, but obviously it's not the most ideal solution).

I'm not really a Rust developer, but these crates exist today and are probably reasonable to use:
- https://docs.rs/directories/latest/directories/
- https://docs.rs/dirs/latest/dirs/

Obviously, as the OP suggests, for backwards compatibility\* reasons you'd definitely still want to check for `RIPGREP_CONFIG_PATH` first and foremost, and only fall back to one of these if it isn't set.

I respect your decision if you still prefer to not deal with this. I just think it's a little unfortunate.

---

\* (and perhaps flexibility, though this wouldn't be so important if it hadn't existed in the first place because options can simply be overridden via the CLI anyway)

**Comment by mvdan** [comment]
It could be that the Rust ecosystem has evolved again on this front, given that it's been six years since my post :) For what it's worth, Go added `os.UserConfigDir` back in 2019 and, while it is overly simplistic and best-effort in how it supports the three main platforms, it's still a good enough practical solution for the majority of projects to house user config and persistent data in. It could be that Rust has gained similar APIs since I filed this issue in 2020. My personal take with these things is to not let perfect be the enemy of the good; I don't need full XDG spec compliance, nor do I develop specifically for Windows or Mac.

**Comment by BurntSushi** [comment]
If we do this, I'd want to use [`etcetera`](https://docs.rs/etcetera/). I've said before somewhere (I can't find it now) that I won't use `dirs` or `directories`. Note in particular that ripgrep should use XDG on macOS.

> With all due respect, personally I don't have a problem with adding another environment variable to my shell config per se, I'll gladly do it. I simply object to the principle that this added friction is an intended part of the user experience in the first place, especially when ripgrep is quite literally the only piece of software I can think of that I use that behaves this way. 

My perspective is not that ripgrep is the odd one out here. Implementations of grep, for example, similarly don't have configuration files. Tools like `ls` and `find` and even `fd` don't either. That's the domain in which ripgrep exists.

With that said, I do find myself more open to this now-a-days. Especially since `etcetera` exists, is battle tested and has a reasonable dependency tree. Longer term, it's looking like XDG support will be added to the standard library, so we'll be able to drop `etcetera` on Unix systems at least once that happens.

I suppoose that if we do this, the format of the config file would remain the same. And I think we'd want to append arguments in order (this is just a concrete example, we'd use the proper paths for real):

* Start with an empty `argv`.
* If `RIPGREP_CONFIG_PATH` is not the same file as `/etc/ripgrep/rc`, then append `/etc/ripgrep/rc` to `argv`.
* If `RIPGREP_CONFIG_PATH` is not the same file as `$HOME/.config/ripgrep/rc`, then append `$HOME/.config/ripgrep/rc` to `argv`.
* Append `$RIPGREP_CONFIG_PATH` to `argv`.

I think the scheme above should be non-breaking to existing use cases. e.g., If someone has `RIPGREP_CONFIG_PATH=$HOME/.config/ripgrep/rc` or whatever. This also nicely solves the problem of specifying a system wide configuration for ripgrep. That in turn might help some cases where [sysadmins want to set default values related to resource usage](https://github.com/BurntSushi/ripgrep/discussions/2968).

Note that we'd still always use XDG config files even when `RIPGREP_CONFIG_PATH` is set. This permits a more granular layered config if folks wanted it. In particular, I don't see any reason why we *shouldn't* do it.

What do people think? cc @okdana for your unfailingly insightful thoughts. :-)

**Comment by lunaynx** [comment]
You're right that if we compare to similar tools like grep, ripgrep is not really an odd one out, because grep et al. often don't provide configuration *at all*. But ripgrep is more complex so it kind of warrants a config file, and in the general context of software with configuration files that are meant for more than just bypassing CLI argument length limit, it feels a bit odd to not have a default path.

I'm fine with XDG on macOS, I'm not married to the idea of using `~/Library/Application Support` especially for CLI tools, but it technically exists as another semi-standard option.

**Comment by thepudds** [comment]
From quick look, it seems `etcetera` allows for some choice in strategy.

Just to slightly expand on @mvdan's [comment](https://github.com/BurntSushi/ripgrep/issues/1719#issuecomment-4809931627) from a few hours ago and as a tiny convenience to anyone following here, I wanted to provide a link to the doc and source code for `os.UserConfigDir` from the Go stdlib:

https://github.com/golang/go/blob/release-branch.go1.26/src/os/file.go#L544-L557

As @mvdan mentioned, it is very simple but has shown to be reasonably useful in practice, so perhaps it is one small data point to think about briefly about when considering choices for `etcetera`. Or maybe it's not useful, in which case sorry for the noise.

(@BurntSushi still has load bearing software running  in the Go ecosystem, but my understanding is he spends less time there nowadays 😅)

**Comment by okdana** [comment]
> What do people think? cc [@okdana](https://github.com/okdana) for your unfailingly insightful thoughts. :-)

idk about that...

> * Start with an empty `argv`.
>
> * If `RIPGREP_CONFIG_PATH` is not the same file as `/etc/ripgrep/rc`, then append `/etc/ripgrep/rc` to `argv`.
>
> * If `RIPGREP_CONFIG_PATH` is not the same file as `$HOME/.config/ripgrep/rc`, then append `$HOME/.config/ripgrep/rc` to `argv`.
>
> * Append `$RIPGREP_CONFIG_PATH` to `argv`.

i like the idea of default paths in general and i think that implementation would be ok, but here are some things that come to mind:

- most tools use their equivalent of `RIPGREP_CONFIG_PATH` to override the user config path entirely -- iow, instead of potentially global -> user -> env like you mentioned, just global -> (env or user). besides being a little simpler to implement, this makes it easier to use a different config on the fly

- i definitely don't like `~/Library/Application Support` for cli tools on macos. it looks like etcetera's 'base strategy' uses xdg there anyway so that's fine

- re: the file name, the three most common approaches i've seen are:

  - `~/.foorc` -> `$XDG_CONFIG_HOME/foo/foorc`
  - `~/.foorc` -> `$XDG_CONFIG_HOME/foo/rc`
  - `~/.foorc` -> `$XDG_CONFIG_HOME/foo/foo.config` (or some variation like `config.foo`, `foo.init`, etc)

  i feel like the `foo/foorc` one might be the most common (used by vim, nano, htop, etc), but `foo/rc` makes sense too (it's basically what git uses)

- re: the global path, some oses / packaging systems don't use `/etc` for non-system packages. e.g. freebsd uses `/usr/local/etc` and pkgsrc (netbsd and others) uses `/usr/pkg/etc`. projects often provide a `configure` flag or similar to override the default path. if you don't do this, packagers will have to maintain their own patches to the source code to change it. this may also be an issue if you have multiple versions of rg on the same system -- due to how naïve its config file is, you can't use newer flags in it or it'll break the older rg. not sure if that concerns you

- there is already a `--no-config` to disable *all* of these files, but the addition of a global file may in the future prompt requests for another flag to disable *just* that one, especially if packagers start adding annoying defaults to it (as some do with e.g. zsh's global zshrc)

- once you add built-in support for global + xdg cli configs, you will probably get requests to do the same with the ignore file

**Comment by BurntSushi** [comment]
@okdana Thank you, that's super helpful. Maybe it would be better to skip the global config file then. Usage with different versions of ripgrep and the likely requests to add more flags to control which things are and aren't loaded seem unfortunate.

With respect to identifying the actual system config file directory, I thought it would just be handled by `etcetera`, but [its implementation](https://github.com/lunacookies/etcetera/blob/master/src/base_strategy/xdg.rs) doesn't seem to have support for `$XDG_CONFIG_DIRS`. Its implementation is also incredibly simple. I imagine I'd just hand-roll it on Unix but use `etcetera` on Windows since it's more complicated there. (I care less about the dependency tree on Windows personally.)

I think I like `~/.config/ripgrep/ripgreprc` better I suppose. The base file name stands more on its own. I don't like the repetition in the path, but I guess it's not a huge deal.

The idea with doing the union of `~/.config/ripgrep/ripgreprc` and `$RIPGREP_CONFIG_PATH` is that one could define their own base level configuration in their `~/.config`, and then layer additional stuff on top of it via `$RIPGREP_CONFIG_PATH`. But maybe that's not worth doing? And it does make the semantic model more complicated. If the system level config is dropped, and we go with your approach, then we just have `$RIPGREP_CONFIG_PATH XOR ~/.config/ripgrep/ripgreprc`, with preference given to `$RIPGREP_CONFIG_PATH` when its both set _and_ non-empty.

> due to how naïve its config file is, you can't use newer flags in it or it'll break the older rg. not sure if that concerns you

Yeah IDK. In theory ripgrep could filter out flags that don't exist (only from config files). But probably not worth doing if we aren't doing system level configs.
