### ISSUE TITLE
broken output with .ripgreprc

### ISSUE THREAD

**Issue by kaldown** [BurntSushi/ripgrep#1729]
`rg value` works as expected
`rg value --glob='!migrations'` works as expected
`rg value` (with .ripgreprc and a single line  `--glob='!migrations'`) produces zero output

RIPGREP_CONFIG_PATH='.ripgreprc'
ripgrep 12.1.1

**Comment by BurntSushi** [comment]
In the future, **please fill out the issue template**. I don't understand why people keep deleting it.

In any case, this is correct behavior. The single quotes are interpreted by the shell. But when you put them in your ripgreprc file, there is no shell interpretation and they are passed verbatim to ripgrep. Since there is no shell interpretation you don't need single quotes to deal with the `!`. So just put `--glob=!migrations` in your ripgreprc. Or alternatively:

```
--glob
!migrations
```
