### ISSUE TITLE
[Security] Vulnerability report

### ISSUE THREAD

**Issue by Ry0taK** [BurntSushi/ripgrep#1773]
I've sent an email that contains the detail of the vulnerability to ![](https://blog.burntsushi.net/images/gmail.png). (As I couldn't find proper contact information to report a vulnerability, I used the email from https://blog.burntsushi.net/about/)
Since I believe this vulnerability can be exploited, I'm not publishing the detail here.

@BurntSushi Can you check the inbox, please?

**Comment by BurntSushi** [comment]
Thanks! That email is fine. I'm investigating it, but since it only happens on Windows, it will take me some time to get to it.

**Comment by BurntSushi** [comment]
Also fixed by https://github.com/BurntSushi/ripgrep/commit/229d1a8d41b0023420e7815578fa0b39c0d5c2e4.

**Comment by Ry0taK** [comment]
@BurntSushi Thank you so much for fixing this issue ;)

**Comment by xfbs** [comment]
This almost sounds like a bug in Windows or `std::process::Command` to me. Other people that are used to *nix might find this behaviour surprising and introduce similar vulnerabilities. Should this be fixed in the stdlib maybe? Maybe have some method on a `Command` that optionally resolves the path to an executable like your `resolve_binary`, overriding the OS's search path (skipping the current working directory)? Just some food for thought (duplicated here because comments on commits might not be the best place).

**Comment by BurntSushi** [comment]
I meant a file a bug against std. The library team did have a brief private conversation about it a couple months ago, and there does seem to be some appetite toward doing _something_ here.

I haven't gotten around to filing an issue, but we are okay doing it publicly. So anyone can create that issue. (And I would invite someone to do it.)

See also: https://github.com/golang/go/issues/38736

**Comment by BurntSushi** [comment]
Note also that I created a CVE for this: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3013

(I sent mail to them to publish the CVE today, so that's pending.)

**Comment by Shnatsel** [comment]
Does this also affect ripgrep being used as a crate? If so, it's probably a good idea to also file an advisory at https://github.com/RustSec/advisory-db - that way people relying on a vulnerable version would be notified through `cargo audit`, `cargo deny`, etc.

**Comment by BurntSushi** [comment]
@Shnatsel Good idea. You're correct!

Done: https://github.com/RustSec/advisory-db/pull/939
