### ISSUE TITLE
--fixed-strings does not find matches with double-quotation marks

### ISSUE THREAD

**Issue by alejandro5042** [BurntSushi/ripgrep#205]
--fixed-strings is having issues matching double-quotes:

![image](https://cloud.githubusercontent.com/assets/3143819/19860315/43a476f0-9f56-11e6-8f9b-be2fedae6414.png)

```
0.01 - C:\Dev\Temp\rg-bug> cat test.txt
[Trait("CAR", "458157")]

0.00 - C:\Dev\Temp\rg-bug> rg '\[Trait\(\"CAR'
test.txt
1:[Trait("CAR", "458157")]

0.03 - C:\Dev\Temp\rg-bug> rg --fixed-strings '[Trait("CAR'

(nothing)
```

But with an escaped double-quote `\"` it works:

![image](https://cloud.githubusercontent.com/assets/3143819/19860386/80dea0fe-9f56-11e6-97e2-e4584053afd1.png)

With `--debug`:

```
0.03 - C:\Dev\Temp\rg-bug> rg --fixed-strings '[Trait(\"' --debug
DEBUG:rg::args: will try to use memory maps
DEBUG:grep::search: regex ast:
Literal {
    chars: [
        '[',
        'T',
        'r',
        'a',
        'i',
        't',
        '(',
        '\"'
    ],
    casei: false
}
DEBUG:grep::literals: literal prefixes detected: Literals { lits: [Complete([Trait(")], limit_size: 250, limit_class: 10 }
test.txt
1:[Trait("CAR", "458157")]
```

**Comment by BurntSushi** [comment]
I can't reproduce the problem:

```
[andrew@Serval tmp] cat foo
[Trait("CAR", "458157")]
[andrew@Serval tmp] rg '\[Trait\("CAR' foo
1:[Trait("CAR", "458157")]
[andrew@Serval tmp] rg -F '[Trait("CAR' foo
1:[Trait("CAR", "458157")]
```

What version of ripgrep are you using?

**Comment by BurntSushi** [comment]
I'll take a look at this. One thing I'd like to know is how other command line search tools operate on Windows. For example, how does `grep -F` work on Windows?

**Comment by alejandro5042** [comment]
Using GNU grep 2.24 from my Git install, no combination of escaping that I can dream up seems to match that line. After a brief search, I can't find much on the Internet on how to do this. Hopefully we can have some input from others here. Even doing nothing, it seems that `rg` is an improvement--there is a way to match that line.

**Comment by BurntSushi** [comment]
In `cmd.exe`, I can't even get single quoted arguments to work at all. Namely, `rg 'Trait'` doesn't find anything. I can make `rg -F "[Trait(\"CAR"` work though.

I note that cygwin doesn't have this behavior. I only get this in cmd.exe, which I think means your analysis is right: this is just due to shell escaping rules. I don't think there's anything ripgrep can really do.

I don't even know what options (2) or (3) mean. I'm inclined to leave this be. If there's a better option and someone submits a PR with tests for it, then I think I'd be OK maintaining it.
