### ISSUE TITLE
improve documentation for replacement group syntax

### ISSUE THREAD

**Issue by Antiever** [BurntSushi/ripgrep#2108]
#### What version of ripgrep are you using?

ripgrep 13.0.0 

#### How did you install ripgrep?

Github binary release

#### What operating system are you using ripgrep on?

Windows 10 Pro 21H2 

#### Describe your bug.

Replace group strange behavior if not separated from text

#### What are the steps to reproduce the behavior?

```
>echo link="https:\\site.com" | rg "(.*)(https.*?)(\")" -or "$1localhost$3"
>"
```
however
```
>echo link="https:\\site.com" | rg "(.*)(https.*?)(\")" -or "$1 localhost$3"
>link=" localhost"
```
Workaround for now is changing regex to insert "" between $1 and text

#### What is the expected behavior?
```
>echo link="https:\\site.com" | rg "(.*)(https.*?)(\")" -or "$1localhost$3"
>link="localhost"
```

**Comment by BurntSushi** [comment]
The behavior here is correct, but it turns out that the docs don't explain how to work around it. You need to use `${1}localhost$3`.

The full docs for the replacement string are here: https://docs.rs/regex/latest/regex/struct.Captures.html#method.expand

More of that should be transplanted into ripgrep's `--help` output, particularly the parts about braces.

**Comment by Antiever** [comment]
Yes, my bad, Thx!

**Comment by BurntSushi** [comment]
This is a documentation bug. Let's leave it open. :-)
