### ISSUE TITLE
Make `--help` shorter

### ISSUE THREAD

**Issue by konsumlamm** [BurntSushi/ripgrep#2194]
`rg --help` currently prints 1145 lines. This is way too long imo, it often takes me a long time to find the flag I'm searching for. For example, `grep --help` by comparison only prints 93 lines. I suggest changing `rg --help` to only print the most common options and introduce a `--fullhelp` flag to print what the `--help` flag currently prints.

**Comment by BurntSushi** [comment]
`rg -h` shows a more condensed output.

**Comment by konsumlamm** [comment]
Ah, thanks, that's good to know. I simply assumed that `-h` and `--help` do the same. Now I also see that the help message actually mentions this:

> Use -h for short descriptions and --help for more details.

**Comment by iliazeus** [comment]
Please consider making `-h` more discoverable! As it stands, the only place I've seen it mentioned (besides this issue) is on the very top of `rg --help` - which is kind of ironic, because calling it without piping into a pager makes the text overflow my terminal's scrollback history, so I never even have a chance to see the `rg -h` hint in the first place.

Alternatively, please consider auto-detecting whether stdout is a tty, and automatically piping `rg --help` output to a pager if it is.
