### ISSUE TITLE
short arg for --files-without-match

### ISSUE THREAD

**Issue by jmhodges-color** [BurntSushi/ripgrep#2292]
#### Describe your feature request

It would be nice if there was a shorter version of the `--files-without-match` argument to ripgrep. While `ripgrep` can't use `-L` (like `grep`, `ag`, and `ack`) because it's taken for `--follow`, it would be nice to have another one.

What do you think about `-K` for that? Or `-W`?

(This is with ripgrep 13.0.0 on macOS 12.5.1 installed via homebrew)

**Comment by BurntSushi** [comment]
Yes, I used `-L` for `--follow` because I suspect it is more common.

I'm not inclined to add a short flag here personally. I think the flag is probably used rarely enough that it doesn't warrant one. And to be honest, neither `-K` or `-W` strike me as particularly good options. `-L` would be the best choice, and if it were available, I would consider adding it as a short flag for `--files-without-match`.

**Comment by BurntSushi** [comment]
I think what I said before still stands today and I'm not inclined to think differently.

I do wish I could go back in time and be a little more careful about the short flags I used. But that ship has sailed.
