### ISSUE TITLE
Automatically determine an appropriate default color scheme on Windows

### ISSUE THREAD

**Issue by retep998** [BurntSushi/ripgrep#248]
By calling `GetConsoleScreenBufferInfoEx` you can inspect the `ColorTable` field to get the current 16 colors for the console. You can then do some fancy stuff using a crate like `palette` to pick colors that have sufficient contrast with the background color (convert from sRGB to CIELAB).

**Comment by BurntSushi** [comment]
I would personally rather solve this issue by making it possible to just choose your scheme. Picking a scheme automatically seems like overengineering and just asking for trouble. See #196 for persistent config.

**Comment by BurntSushi** [comment]
In particular, can you point to other CLI tools that implement the desired functionality?

**Comment by sergeevabc** [comment]
Some color changes happened this year, they became dull.
Is there a way to bring back vivid blue and red to make it easier to distinguish?

![](http://images.vfl.ru/ii/1509874813/a36b32e4/19286891.png)

**Comment by BurntSushi** [comment]
@sergeevabc That question seems unrelated to this issue? Please just open new issues in that case.

You can change colors with the `--colors` flag. Please read the documentation. There is even a tip in the README: https://github.com/BurntSushi/ripgrep#how-do-i-make-the-output-look-like-ags

**Comment by sergeevabc** [comment]
Sorry if my decision to not create a duplicate turned out to be wrong. I am not so immersed in the development to say for sure whether question is related to what was discussed earlier or not, but @retep998 dreamed about colors with sufficient contrast against background by default on Windows and his dream seemed very in line with mine.

I searched for the documentation on colors in the past, but found none. Tip about AG’s color scheme on the frontpage is too fresh to be noticed, a 2 days old commit. Nevertheless I’m looking for more saturated (or [accessible][1] as would my ophthalmologist, a man of science, say) Ripgrep’s defaults out of the box (it promises sane defaults after all), not to be tuned to look like some other grep tool with a help of poorly memorized sequence of extra switches.

[1]: https://encrypted.google.com/search?q=contrast+tool+accessibility

**Comment by BurntSushi** [comment]
> I searched for the documentation on colors in the past, but found none. 

It's right there in the output of `rg --help`. As I said before, look for the `--colors` flag. It's also in the man page.
