### ISSUE TITLE
Automatically ignore other git worktrees?

### ISSUE THREAD

**Issue by jeanas** [BurntSushi/ripgrep#2492]
#### Describe your feature request

When ran inside a Git repository, I would appreciate if ripgrep could only reports results from that worktree, but not from other worktrees that may be inside it. This is the behavior of `git grep`:

```
~/repos/lilypond $ git grep "parse_embedded_scheme"
lily/include/parse-scm.hh:31:SCM parse_embedded_scheme (const Input &start, Lily_parser *parser,
lily/lexer.ll:364:      SCM sval = parse_embedded_scheme (start, parser_, &parsed);
lily/lexer.ll:413:      SCM sval = parse_embedded_scheme (hi, parser_, &parsed);
lily/lexer.ll:429:      SCM sval = parse_embedded_scheme (hi, parser_, &parsed);
lily/parse-scm.cc:214:internal_parse_embedded_scheme (void *p)
lily/parse-scm.cc:268:parse_embedded_scheme (const Input &start, Lily_parser *parser,
lily/parse-scm.cc:274:  SCM result = scm_c_catch (SCM_BOOL_T, internal_parse_embedded_scheme, &ps,
~/repos/lilypond $ rg "parse_embedded_scheme"
lily/parse-scm.cc
214:internal_parse_embedded_scheme (void *p)
268:parse_embedded_scheme (const Input &start, Lily_parser *parser,
274:  SCM result = scm_c_catch (SCM_BOOL_T, internal_parse_embedded_scheme, &ps,

lily/include/parse-scm.hh
31:SCM parse_embedded_scheme (const Input &start, Lily_parser *parser,

master/lily/lexer.ll
364:	SCM sval = parse_embedded_scheme (start, parser_, &parsed);
413:	SCM sval = parse_embedded_scheme (hi, parser_, &parsed);
429:	SCM sval = parse_embedded_scheme (hi, parser_, &parsed);

lily/lexer.ll
364:	SCM sval = parse_embedded_scheme (start, parser_, &parsed);
413:	SCM sval = parse_embedded_scheme (hi, parser_, &parsed);
429:	SCM sval = parse_embedded_scheme (hi, parser_, &parsed);

master/lily/include/parse-scm.hh
31:SCM parse_embedded_scheme (const Input &start, Lily_parser *parser,

master/lily/parse-scm.cc
214:internal_parse_embedded_scheme (void *p)
268:parse_embedded_scheme (const Input &start, Lily_parser *parser,
274:  SCM result = scm_c_catch (SCM_BOOL_T, internal_parse_embedded_scheme, &ps,
```

I frequently use worktrees for things like performance comparisons of a feature branch to the master/main branch. When I use `rg`, I just want to search the code base (under the version I'm working on), but not get duplicated search results from other (a bit different) copies of the same source code.

**Comment by BurntSushi** [comment]
Please provide a way to reproduce the behavior today that you don't want, and then please show the behavior that you do want. Someone else (i.e., me) should be able to run the same commands.

**Comment by BurntSushi** [comment]
Thank you, that makes it much clearer. I'm not sure automatically ignoring these is the right approach. It seems somewhat surprising to do so, especially since the worktree might have different contents than its "primary" checkout.

I think I'd rather see you use `.rgignore` to specifically and explicitly ignore these worktrees.

**Comment by BurntSushi** [comment]
I thought about this and I think the juice isn't worth the squeeze.

Firstly, it's not totally obvious to me that the default behavior _ought_ to be to not search these sub-directories. ripgrep already searches git repos within git repos (a common setup when `$HOME` is a git checkout). I admit that reasonable people could disagree, and in theory a flag could be added for folks to opt into this.

But secondly, I think it should be pretty straight-forward to "work around" this instead of adding a flag to ripgrep. This is what things like `.rgignore` are for.
