### ISSUE TITLE
Commit 4fcb1b2202b97c5a21894672232700225223a138 breaks build from source on Ubuntu 18.04LTS

### ISSUE THREAD

**Issue by toddin8tor** [BurntSushi/ripgrep#2534]
#### What version of ripgrep are you using?

Attempting to build from source for 32-bit Ubuntu 18.04LTS Docker image. No 32-bit precompiled images available to download. Rustc version is 1.65.

#### How did you install ripgrep?

snippet from Dockerfile...
```Dockerfile
 RUN (cd /usr/local; git clone https://github.com/BurntSushi/ripgrep) && \
      (cd /usr/local/ripgrep; cargo build --release) && \
      (cd /usr/local/bin; ln -s ../ripgrep/target/release/rg)
```

NOTE: this worked fine prior to this commit. My short term workaround is to checkout the commit prior to this breaking change. (949092fd22689905fce358cdd1b2b676709feefe)

#### What operating system are you using ripgrep on?

Ubuntu 18.04LTS (32-bit)

#### Describe your bug.

There is no std::io::IsTerminal in rustc 1.65. As commit message says, requires 1.7 or later.

#### What are the steps to reproduce the behavior?

see Dockerfile snippet above...

#### What is the actual behavior?

Build fails with message about std::io:IsTerminal can not be found.

#### What is the expected behavior?

What do you think ripgrep should have done?

Should just build.

The suggested fix is to see if the newer std::io::IsTerminal stuff is available with a test compile of something small and use the old atty crate if not.

**Comment by BurntSushi** [comment]
No this isn't a breaking change. You're using an old version of `rustc`. You have two choices. You can either upgrade your version of Rust or you can build an older version of ripgrep.

**Comment by toddin8tor** [comment]
With respect,

It actually is a breaking change.

Yes, I'm using an old distro with its fairly ancient rust. There's a very good reason for that... I'm supporting a very old product where certain ICs are EOL'd In order to add drivers for replacement parts into the kernel for that product, I have to recreate the build env for the ancient Yocto build it's based on.

Ripgrep is an awesome tool... one of my daily gotos. It's pretty sad that it looks like I'll have to fork the repo to get any future bugfixes or enhancements when the fix for this is pretty simple.

-- 
  Todd Weybrew
  Principal, Warp 9 Designs, LLC
  ***@***.***

**Comment by BurntSushi** [comment]
It actually isn't. Tools require new versions of toolchains all of the time. The problem here is you want me to maintain support for older toolchains on ***YOUR*** schedule. But I've never made that promise. Indeed, ripgrep's README *specifically* states that it tracks the **latest stable release of Rust**. That sounds like too fast of a pace for you, but that's on you. I'm not here to give you free labor on your schedule.

> It's pretty sad that it looks like I'll have to fork the repo to get any future bugfixes or enhancements when the fix for this is pretty simple.

It's not sad at all. It's working exactly as intended. You have a financial incentive to maintain older toolchains and are getting paid to do it. I'm not. It makes sense that you need to maintain a fork to get what you need to meet the demands of your product.

Have fun.
