### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by DamienCassou** [BurntSushi/ripgrep#2540]
The previous 13.0.0 is 2 years old and this is what [most distributions are using](https://repology.org/project/ripgrep/versions). Do you think a new release could be done so everyone benefits from all the recent hard work?

**Comment by BurntSushi** [comment]
https://github.com/BurntSushi/ripgrep/blob/master/FAQ.md#release

**Comment by BurntSushi** [comment]
The reason why there hasn't been a release is partly because I became a father and partly because I've spent most of my free time working on https://github.com/rust-lang/regex/issues/656. Where the latter is the regex engine used by ripgrep. That is coming to a close (for now) soon. Probably soonish thereafter I'll put out a new release of ripgrep. But I can't tell you when it will be. It could be next month. It could be next year.

**Comment by DamienCassou** [comment]
Thank you very much for your answer and congrats for your child!
