### ISSUE TITLE
Why don't release new version

### ISSUE THREAD

**Issue by ahczbhht1989** [BurntSushi/ripgrep#2647]
I see the recent the version is 13.0.0 build in 2021.after that we develop some feature and fix some bugs,Why doesn't release new version for use.

**Comment by BurntSushi** [comment]
Because:

* I do this in my spare time.
* I have a small child which makes my spare time incredibly limited.
* I spent most of my spare time over the last three years [rebuilding ripgrep's regex engine](https://blog.burntsushi.net/regex-internals/).
* There hasn't been a pressing need to put out a new release.
* I try hard to amortize my work. This means I can take long sabbaticals from individual projects with occasional bursts of activity.

I have been working on the next release for the last couple months. It will be ready when it's ready.
