### ISSUE TITLE
detect simd and avx features during runtime?

### ISSUE THREAD

**Issue by vladon** [BurntSushi/ripgrep#265]
I'm building deb package (for myself) of ripgrep, and want to distribute it to machines with and without SIMD and AVX.

Is it possible that ripgrep will detect SIMD and AVX features at runtime and use or not use them accordingly?

**Comment by BurntSushi** [comment]
Nope. Two reasons:

1. Firstly, I'm assuming you need to compile ripgrep with stable Rust. If so, SIMD isn't supported so you couldn't enabled it even if you wanted to.
2. Rust doesn't have runtime CPU feature detection yet. We're working on a proposal to get that (and various other SIMD things) stabilized, but it will be months (or more) before it makes its way to stable Rust.

I'm going to close this because it should eventually happen automatically.

**Comment by vladon** [comment]
OK, it was just a question.
In Rust, can we write CPU detection (actually running `cpuid` instruction)?

**Comment by BurntSushi** [comment]
@vladon You would have to write Assembly to check the cpuid and link it into your Rust binary (Rust doesn't have an otherwise stable way of accessing `cpuid` information). Even if we did that, it's not sufficient, because you need compiler support for emitting SIMD intrinsics. (In Clang and gcc, this is the `__attribute__(__target__)` feature.) We don't have that yet either. Soon though!
