### ISSUE TITLE
FR: sort results by count

### ISSUE THREAD

**Issue by etiennepellegrini** [BurntSushi/ripgrep#2769]
I'd love to see a `count` option to `--sort` and `--sortr`, to be able to sort files according to the number of matches.
Both `--sort=count` and `--sort=count-matches` would be ideal!

Thanks!

**Comment by BurntSushi** [comment]
This is probably not going to happen, because it would require buffering _everything_ into memory (including all of the matches from all of the files), sorting it and then printing. Currently, the existing sort options only require buffering the file paths to search into memory. (Which is bad enough already.)
