### ISSUE TITLE
add option for structured output

### ISSUE THREAD

**Issue by lzybkr** [BurntSushi/ripgrep#32]
Consider adding a flag to output structured data such as json or csv for use by other tools.

`rg --color None --no-heading` is nearly good enough, but the extent of the match is missing.

**Comment by BurntSushi** [comment]
Can you use the `--vimgrep` flag for this?

It feels a little off to support CSV or JSON in a tool like this to be honest, but I'm not strongly opposed.

**Comment by lzybkr** [comment]
`--vimgrep` is roughly CSV but with `:`, so that works. It's missing the length though.

**Comment by BurntSushi** [comment]
I'm going to close this in favor of #162. I feel like supporting this would add significant complexity, because every single flag that controls output needs to be re-interpreted based on the output format.

Once #162 is done and there exists a straight-forward path to support this, then I'd be happy to maintain a well tested implementation in ripgrep proper.
