### ISSUE TITLE
experiment with Windows memory map flags

### ISSUE THREAD

**Issue by BurntSushi** [BurntSushi/ripgrep#328]
```
[18:08] * WindowsBunnyDancingOnRainbows wonders if burntsushi hints sequential access in ripgrep
[18:08] <WindowsBunnyDancingOnRainbows> Ralith: Well there are functions to hint to the OS you'll be using memory soon so it'll prefetch it
[18:09] <burntsushi> WindowsBunnyDancingOnRainbows: i don't do anything special with mmaps. i just open them and search.
[18:09] <WindowsBunnyDancingOnRainbows> burntsushi: You search sequentially though?
[18:09] <burntsushi> yes
[18:10] <WindowsBunnyDancingOnRainbows> burntsushi: Then you *really* want to pass FILE_FLAG_SEQUENTIAL_SCAN when opening the file
[18:10] <WindowsBunnyDancingOnRainbows> Both with and without mmaps
[18:10] <burntsushi> WindowsBunnyDancingOnRainbows: is that supported by the memmap crate?
[18:10] <WindowsBunnyDancingOnRainbows> burntsushi: Does memmap support opening from an fs::File?
[18:10] <burntsushi> i believe so
[18:11] <WindowsBunnyDancingOnRainbows> burntsushi: Then you can use the OpenOptionsExt on Windows to open an fs::File with that flag, then use it or pass it to memmap
```

**Comment by CannedYerins** [comment]
Hi @BurntSushi, do you have any recommendations on how to benchmark this?  It looks like everything in benchsuite is Linux only.

**Comment by retep998** [comment]
Also, note that `FILE_FLAG_SEQUENTIAL_SCAN` should be set on all your files, not just your memory maps.

**Comment by BurntSushi** [comment]
@CannedYerins I think the only thing in `benchsuite` that is Linux only is building the Linux kernel.

If `benchsuite` is too inconvenient to run on Windows, then I think we'll need to come up with our own benchmark for this. It should include short and long files, as well as a small number of files and a large number of files.

**Comment by CannedYerins** [comment]
Hmm, you're right - mostly.  I could get the Linux stuff working if I commented out both the build and rewrote has_linux() to ignore that we haven't built.  Additionally, the gunzip command is not available for the subtitles, though it is included in Git for Windows' shell, so I was able to just do that step manually and rerun to continue.  Finally, strangeness with Windows encodings meant that I had to set the PYTHONIOENCODING environment variable to utf-8 for the printed output to work and open the CSV file with the additional encoding='utf-8' argument (this being for printing the ru benchmark names).

I'm benchmarking this on Windows Server 2016 on GCE instead of AWS because you can use beefier GCE machines on the trial :).  My own machine was too weak and noisy.  The GCE machine has 30gb of RAM (overkill) and 8 vCPUs.  And it'd probably be most ideal to do it headless, but I have no idea how to PowerShell so I'm doing it with the GUI.

So, here's what I've actually done:
First, I wrote and tested https://github.com/CannedYerins/ripgrep/commit/3b0938f015767248c20ef3dee1a50e6c1bb4f52d on my machine.  
Then, on the GCE instance, I installed Git for Windows, cloned my fork, installed Rust (with its VS dependencies), installed Python, `cargo install`ed my local ripgrep, made the changes to benchsuite described above, and ran the full suite.  Then, I unapplied my changes and ran again, committing the results in https://github.com/CannedYerins/ripgrep/commit/9cc9ebf1b34b89f444e47a10336a9863fe6c37d9 (it looks like the line endings are borked in the CSV files, eep).

I ran `python benchsuite --disabled 'grep,git' --allow-missing --raw raw.csv | tee summary` so that just rg would run.

So comparing the baseline https://github.com/CannedYerins/ripgrep/blob/master/benchsuite/runs/2017-02-04-windowsserver2016-gce/summary to the modification https://github.com/CannedYerins/ripgrep/blob/master/benchsuite/runs/2017-02-04-windowsserver2016-gce-seqflag/summary, it looks like there isn't any decisive improvement.

What do you think?

**Comment by retep998** [comment]
If you run the benchmark over and over that flag won't have much difference because the file is already cached in memory. It is when you're reading a large file from disk and it hasn't been cached in memory yet, that is when there is a noticeable improvement. Instead of getting a big beefy machine with 30GB of ram, try using something with much less RAM and benchmark it on files that are *bigger* than your RAM (that way it can't cache the whole file in memory).

**Comment by CannedYerins** [comment]
Got it, I'll give that a go.

**Comment by CannedYerins** [comment]
Used a machine with 4GB of ram (~1GB taken by the OS/other processes), running only the English subtitles benchmarks (which run on the same 9.3GB file), with no repetitions, things look more convincing.

Without flag:
```
$  python benchsuite --disabled 'grep,git' --allow-missing --raw without_flag.csv --bench-iter 1 --warmup-iter 0 --force 'subtitles_en' | tee without_flag.txt
subtitles_en_alternate (pattern: Sherlock Holmes|John Watson|Irene Adler|Inspector Lestrade|Professor Moriarty)
---------------------------------------------------------------------------------------------------------------
rg (lines)     2.953 +/- 0.000 (lines: 848)
rg*            2.812 +/- 0.000 (lines: 848)*

subtitles_en_alternate_casei (pattern: Sherlock Holmes|John Watson|Irene Adler|Inspector Lestrade|Professor Moriarty)
---------------------------------------------------------------------------------------------------------------------
rg*            3.078 +/- 0.000 (lines: 862)*

subtitles_en_literal (pattern: Sherlock Holmes)
-----------------------------------------------
rg*            0.500 +/- 0.000 (lines: 629)*
rg (no mmap)   0.719 +/- 0.000 (lines: 629)
rg (lines)     0.609 +/- 0.000 (lines: 629)

subtitles_en_literal_casei (pattern: Sherlock Holmes)
-----------------------------------------------------
rg*                   2.812 +/- 0.000 (lines: 642)*
rg (lines)            2.906 +/- 0.000 (lines: 642)

subtitles_en_literal_word (pattern: Sherlock Holmes)
----------------------------------------------------
rg (ASCII)     0.625 +/- 0.000 (lines: 629)
rg*            0.609 +/- 0.000 (lines: 629)*

subtitles_en_no_literal (pattern: \w{5}\s+\w{5}\s+\w{5}\s+\w{5}\s+\w{5}\s+\w{5}\s+\w{5})
----------------------------------------------------------------------------------------
rg             2.875 +/- 0.000 (lines: 13)
rg (ASCII)*    2.531 +/- 0.000 (lines: 13)*

subtitles_en_surrounding_words (pattern: \w+\s+Holmes\s+\w+)
------------------------------------------------------------
rg             0.641 +/- 0.000 (lines: 317)
rg (ASCII)*    0.609 +/- 0.000 (lines: 317)*
```

With flag:
```
$  python benchsuite --disabled 'grep,git' --allow-missing --raw with_flag.csv --bench-iter 1 --warmup-iter 0 --force 'subtitles_en' | tee with_flag.txt
subtitles_en_alternate (pattern: Sherlock Holmes|John Watson|Irene Adler|Inspector Lestrade|Professor Moriarty)
---------------------------------------------------------------------------------------------------------------
rg (lines)     2.891 +/- 0.000 (lines: 848)
rg*            2.734 +/- 0.000 (lines: 848)*

subtitles_en_alternate_casei (pattern: Sherlock Holmes|John Watson|Irene Adler|Inspector Lestrade|Professor Moriarty)
---------------------------------------------------------------------------------------------------------------------
rg*            2.984 +/- 0.000 (lines: 862)*

subtitles_en_literal (pattern: Sherlock Holmes)
-----------------------------------------------
rg*            0.453 +/- 0.000 (lines: 629)*
rg (no mmap)   0.688 +/- 0.000 (lines: 629)
rg (lines)     0.594 +/- 0.000 (lines: 629)

subtitles_en_literal_casei (pattern: Sherlock Holmes)
-----------------------------------------------------
rg*                   2.766 +/- 0.000 (lines: 642)*
rg (lines)            2.875 +/- 0.000 (lines: 642)

subtitles_en_literal_word (pattern: Sherlock Holmes)
----------------------------------------------------
rg (ASCII)*    0.609 +/- 0.000 (lines: 629)*
rg             0.609 +/- 0.000 (lines: 629)

subtitles_en_no_literal (pattern: \w{5}\s+\w{5}\s+\w{5}\s+\w{5}\s+\w{5}\s+\w{5}\s+\w{5})
----------------------------------------------------------------------------------------
rg             2.859 +/- 0.000 (lines: 13)
rg (ASCII)*    2.516 +/- 0.000 (lines: 13)*

subtitles_en_surrounding_words (pattern: \w+\s+Holmes\s+\w+)
------------------------------------------------------------
rg*            0.594 +/- 0.000 (lines: 317)*
rg (ASCII)     0.609 +/- 0.000 (lines: 317)
```

**Comment by CannedYerins** [comment]
Hi @BurntSushi, any thoughts on this?

**Comment by BurntSushi** [comment]
@CannedYerins Thanks for doing this! It looks like there is virtually no difference to me. You ran the benchmarks with only a single iteration, so it's impossible to see the variance to make a final determination. The other problem is that 4GB of RAM is enough to fit all of the benchmark corpora in memory. :-(

The other issue here is that you're only passing the seq scan flag when opening a file for buffered reading, but ripgrep is probably using memory maps in all of the subtitle benchmarks, which I think means you aren't actually measuring what you want to measure. :-( See the mmap logic here: https://github.com/BurntSushi/ripgrep/blob/master/src/args.rs#L564

**Comment by BurntSushi** [comment]
I'm going to close this because I don't see much value in tracking it. Given my ignorance of Windows, I wouldn't be surprised if someone could make ripgrep go faster via some Windows-specific tweaks. But I don't have the bandwidth to do it.
