### ISSUE TITLE
Feature idea: "context matches"

### ISSUE THREAD

**Issue by quodlibetor** [BurntSushi/ripgrep#346]
I "often" find myself doing something like:

```
$ rg -A5 something | grep -B5 something-else
```

it would be kind of awesome if `rg` took a `--context-matches` regex (that requires one of the other context specifiers (`-A -B -C`)) that does this automatically for me.

```
$ rg -A5 -B2 --context-matches 'some.regex' 'main.search'
...
```

```
$ rg --context-matches 'some.regex' 'main.search'
error: --context-matches requires one of --before, --after, or --context
```

**Comment by BurntSushi** [comment]
I'm not against this on principle, but it would be a very difficult feature to add in the current implementation.

**Comment by quodlibetor** [comment]
Ah, that makes sense. I was hoping that it would be as simple as just caching the output for each chunk for a bit and running a regex over that cached chunk.

**Comment by quodlibetor** [comment]
Which is obviously less efficient than some kind of fancy one-pass analysis.

**Comment by timotheecour** [comment]
related to: https://github.com/BurntSushi/ripgrep/issues/360

**Comment by BurntSushi** [comment]
> I was hoping that it would be as simple as just caching the output for each chunk for a bit and running a regex over that cached chunk.

The current implementation already does that. It *has* to, because it doesn't know which lines to print until a match occurs.

You're welcome to go look at the code and marvel at just how hard an addition like this would be. The context handling is complicated, which is why I've tagged this with `libripgrep`. Namely, we should think about this use case while refactoring the search code into a reusable library.

**Comment by Hywan** [comment]
Hello,

It might sound stupid, but what would be the difference between:

```
$ rg --context-matches 'foo' 'bar'
```

and:

```
$ rg 'foo.*bar'
```

**Comment by BurntSushi** [comment]
ripgrep doesn't do multiline search.

**Comment by BurntSushi** [comment]
I'm going to close this not only because the implementation complexity of this scares me a little, but it opens the door to a whole new world of feature bloat that I'd rather avoid. I'd kindly suggest that if someone wants a search this sophisticated, they should just write some code or figure out a clever work-around using the existing context flags. :-)

**Comment by jdtsmith** [comment]
A related idea that might be much easier to implement: a _context state_ match.  Rather than printing lines before or after the match, a context match would print the most recent matching line, if any.  Any given context match is only printed (once) when the main match hits.  So with a file like:

```
* foo
** bar
*** baz
something
*boo
something else
```

and `rg --context-match '^\*+' something` would produce:

```
*** baz
something
* boo
something else
```
