### ISSUE TITLE
Zero length matches don't colourise properly

### ISSUE THREAD

**Issue by filterfish** [BurntSushi/ripgrep#366]
I use this little grep command to highlight keywords, in for example, logs (or in this case packages):

```bash
apt-cache search cudf | grep -E --colour '^|cudf'
```
When I use `rg '^|cudf'` it doesn't colourise the matches that match `^cudf` which is incorrect.

Anyway I've attached two screenshots to show the difference (I couldn't work out how to set the colours in Markdown!). Note the difference in brightness  is simply due to my compositor settings and nothing to do do with this issue.

grep: 
![colours-grep](https://cloud.githubusercontent.com/assets/12899/23057368/f3f594c4-f543-11e6-8b18-b599ee312276.png)

rg:

![colours-rg](https://cloud.githubusercontent.com/assets/12899/23057376/029fe128-f544-11e6-9630-ae38289a1610.png)

**Comment by BurntSushi** [comment]
Interesting. This is an artifact of the regex engine and I'm not sure there's much that can be done. In particular, the regex engine has *leftmost first* matching semantics (which means that the first branch in an alternation that matches is used), which tends to match the behavior that most folks expect because they are the default matching semantics of backtracking engines. Most finite automata based engines provide *leftmost longest* matching semantics (which means that the branch in an alternation that matches the most text is used), including the one inside of GNU grep. For example, while you get your desired results with `grep -E`, if you try `grep -P` (which uses PCRE), you will see the same behavior as ripgrep.

I think the only work-around available to you is to encode the match priority you want. For example, instead of `rg '^|cudf` use `rg 'cudf|^'`.

**Comment by filterfish** [comment]
Blimey. And there was me thinking I had an OK understanding of regexes. Clearly I was way of the mark!
Thanks for the in-depth reason as to why and the workaround; I hadn't thought of that.

**Comment by BurntSushi** [comment]
Yeah, match priority in alternations is tricky business. It is occasionally useful though. :-)
