### ISSUE TITLE
Feature: Display control characters using caret notation

### ISSUE THREAD

**Issue by casey** [BurntSushi/ripgrep#379]
I was using `rg` today and it started printing results from a binary file.

The file in question starts with a bunch of text, but ends with an inline zip file, which I think confused ripgrep's binary file type detection.

The results included a lot of control characters, which hosed my terminal.

Would it be possible to print control characters in the output using caret notation? In the general case, I'm not sure that non-printable control characters are useful in results, so it might be worth it to turn this on by default, but it could also live behind a flag.

**Comment by BurntSushi** [comment]
Do other tools do this? e.g., grep? If grep detects your file as binary, then I'd like to learn how ripgrep can make its detection better.

I'm pretty hesitant to go down the path of completely rewriting output results, but I agree that messing up your terminal is not a pleasant experience.

**Comment by casey** [comment]
Grep does indeed detect it as binary.

Using `grep -r pattern .` I get `Binary file ./weird-file matches`

How does ripgrep's binary file type detection currently work?

The issue is that this particular file starts with a bunch of plain test, so any heuristic that uses the beginning of the file will fail here.

**Comment by casey** [comment]
The file utility seems to notice that it contains binary:

```
$ file wierd-file
wierd-file: Bourne-Again shell script executable (binary data)
```

**Comment by BurntSushi** [comment]
@casey Binary detection is basically "find a `NUL` byte." ripgrep had a bug (that's fixed on master) where it only looked at the first 1KB or so for a `NUL` byte. Unfortunately, that bug is only fixed when buffered reading is used. If ripgrep decides to use memory maps, then I think it only examines the first 10KB.

**Comment by casey** [comment]
Hmmm, in that case I think there is always a risk that it will misdetect the type of a file.

Although it sounds weird, I think this situation comes up more often than one might expect. In this case, the file is a self-extracting python binary. The file is a shell script followed by a zip archive, where the shell script extracts the zip archive.

This gets a lot of use at both facebook and google (I'm a current facebook employee and ex google employee), and seems to be used in chromeos: https://chromium.googlesource.com/chromiumos/platform/factory/+/stabilize-4068.0.B/py/tools/make_par.py (not sure for what though)

**Comment by BurntSushi** [comment]
I'm going to close this. My feeling is that this isn't ripgrep's responsibility, and that it should be possible to pipe output of ripgrep into another program that does this sanitization for you. One might argue that this limits the utility of such a feature since you generally don't know whether your terminal is going to get hit with a bunch of control sequences. But this would be true if we did it in ripgrep as well. In particular, there is no way we could enable such a filter by default because of the performance impact that would have. So it would need to be opt-in.
