### ISSUE TITLE
Strange searching through stdin. Windows

### ISSUE THREAD

**Issue by DoumanAsh** [BurntSushi/ripgrep#431]
There is strange behavior when printing results of search through stdin:
```
> cat .\src\search_stream.rs | rg "lock\(\)"
    let mut rdr = snap::Reader::new(stdin.lock());
    let mut wtr = stdout.lock();
/baz.rs:10:    let mut rdr = snap::Reader::new(stdin.lock());
/baz.rs-10-    let mut rdr = snap::Reader::new(stdin.lock());
/baz.rs:11:    let mut wtr = stdout.lock();
/baz.rs:10:    let mut rdr = snap::Reader::new(stdin.lock());
/baz.rs-11-    let mut wtr = stdout.lock();
```

It seems rather inconsistent i suppose?

**Comment by BurntSushi** [comment]
Why do you think this is an issue with `stdin`? If you search the file directly, do you get the same results?

As far as I can see, the output looks correct. You might be getting confused because of some of the unit tests in `search_stream.rs`. Go do a `^F` for `lock()` in https://github.com/BurntSushi/ripgrep/blob/master/src/search_stream.rs

**Comment by DoumanAsh** [comment]
Sorry about that :(
