### ISSUE TITLE
Feature Request msi installer on windows

### ISSUE THREAD

**Issue by technician77** [BurntSushi/ripgrep#550]
What is your oppinion on providing a msi installer for it? Chocolatey is not a viable option in a business environment. You might say an installer is overkill for a small utility like this but then again it solves a lot of problems for the inexperienced user. And it's the "windows-way". You can always tell windows users go to this site, install this exe and you are good to go. When telling them "and now you just add that folder to the PATH variable" they be like ????. You might say, show me another reputable command-line project that offers an installer. Check out pandoc: [https://github.com/jgm/pandoc/releases](https://github.com/jgm/pandoc/releases)

**Comment by BurntSushi** [comment]
At a high level, ripgrep is a command line utility. It does not have a GUI, so in order to use it, you must already have some comfort on the command line itself. Could you say more about the users that you think would benefit from ripgrep but do not know how to set their `PATH` (or put the `exe` in a folder that is already in their `PATH`)?

More specifically, I'm not opposed to this, but:

1. It has to be automated and easy to maintain.
2. I don't know how to do it.

**Comment by technician77** [comment]
Must you? Not if the user installs also a program that acts as a gui for rg.
1. Sure it has.
2. Makes us two
Sorry, I can't be much of a help, but maybe you can add that to the future feature list, and somebody steps up to do the job. I just think that if you make the claim 

> ...first class support on Windows...

 on the front page an installer would be apt.

**Comment by BurntSushi** [comment]
First class support means the tool works and that releases are gated on the Windows build passing tests. Getting an executable that works out of the box on Windows is exactly as good as what you get from me for Linux and Mac.

Sorry, but I'm still not following. ripgrep is a command line tool. There is no GUI component. The only way to use ripgrep is to run it on the command line. What advantage does an installer bring? If there's some other GUI tool that wants to use ripgrep, then why can't they package it up in their own installer?

**Comment by technician77** [comment]
They could, but what if your tools gets an update. They would be forced to update also to be on par. Well ultimatively it's not needed, it would be just a small convenience. Linux Distros provide similar installation convenience using repositories. Since windows has no repos, providing this convenience is up to the individual app dev.

**Comment by elirnm** [comment]
@technician77 If what you want is a package-manager-like experience on Windows, you can use [Chocolatey](https://chocolatey.org/), which has a [ripgrep package](https://chocolatey.org/packages/ripgrep).

**Comment by technician77** [comment]
I know, but as stated in the original post: 
> chocolatey is not a viable option in a business environment.

Or am I wrong here? I've seen on their site they are going for business now, but can this approach of moderated packages, mostly created by different individuals than the software authors, be considered safe? A simple standalone installer directly from the software author seems to me the safer approach here.

**Comment by BurntSushi** [comment]
We should consider a Windows installer **on its own merits**. There are a huge amount of unknowns still before I would feel comfortable saying "yes we should do this." I would like to see **concrete answers** to the following things:

1. What work is required in creating an installer?
2. What work is required in maintaining an installer?
3. What specific benefits does an end user get with an installer that they don't get with just downloading the executable directly?
4. What are the characteristics of a "business environment" that make one solution impossible but another solution possible?
5. What is the relationship between ripgrep, an installer and some other GUI tool that might want to use ripgrep? How would such a tool benefit from ripgrep having an installer? Why can't the GUI tool bundle ripgrep?

**Comment by okdana** [comment]
Maybe [Ninite](https://ninite.com/) could be convinced to distribute ripgrep? A lot of the Windows users i know seem to like that for installing stuff.

**Comment by technician77** [comment]
Well it seems, there are usecases for an installer see #420.

If an installer is too much work, how about at least a powershellscript that adds the current directory to PATH and another one that removes it?

Ninite looks great, but I don't think a tiny GUI-less tool like ripgrep fits into the existing portfolio.

I don' think I'm qualified enough to give anwers to any of the questions above. Maybe some comments to some questions:
3. There might be more...
- The "standard" solution of app installation in windows. Acknowleged by noobs and companies.
- "Visibility" of the app in the system for inventory systems, GUIs and endusers
-  Automatic PATH setting during installation
- GUI Deinstallation with removal of PATH setting.
4. 3rd party is certainly a factor that complicates approval processes.
5. Mostly bundling is not a good idea. Problems are update-synchonisation, 3rd party involvement and unwanted bloat.

**Comment by BurntSushi** [comment]
> Problems are update-synchonisation

I don't think this can be characterized as a problem. If anything, it's a trade off. Bundling is useful because it means there will never be a version mismatch between what the tool expects and what ripgrep actually does. For example, if a new release of ripgrep changes some behavior that the other tool depends on, then the tool might break. If ripgrep is bundled, then behavior always remains the same.

**Comment by BurntSushi** [comment]
I'm going to close this because I don't see any compelling motivation to actually do this. If someone can answer my [previous questions](https://github.com/BurntSushi/ripgrep/issues/550#issuecomment-315544614) in sufficient detail and provide compelling motivation then we can re-open this, but I can pretty much promise you that if that increases the burden of work I need to do during a release, then I'm probably not going to want to do it.
