### ISSUE TITLE
globset and matching against current cwd

### ISSUE THREAD

**Issue by mqudsi** [BurntSushi/ripgrep#564]
It seems that `globset` requires pathed filters, i.e. `*.jpg` does not match `./something.jpg`, instead, the filter `./*.jpg` must be used.

Currently, I pass all expressions to a function called `fix_filters` first before passing them to the glob builder, then I pass only "pathed" values to globset.is_match (i.e. either a path starting with `/` (absolute path) or `.` for relative paths like ../something or ./something).

_If_ globset is intended to be used for paths and not general strings, then you might consider doing that automatically? Or else modifying the regexp to match `^(|./)` for unpathed expressions?

**Comment by BurntSushi** [comment]
Could you please show some code the reproduces the issue? I cannot reproduce the issue. The following program

```rust
extern crate globset;

use globset::Glob;

fn main() {
    let g = Glob::new("*.jpg").unwrap().compile_matcher();
    println!("{:?}", g.is_match("./something.jpg"));
    println!("{:?}", g.is_match("something.jpg"));
}
```

outputs

```
$ cargo run
true
true
```

Are you perhaps enabling the [`literal_separator`](https://docs.rs/globset/0.2.0/globset/struct.GlobBuilder.html#method.literal_separator) option? (It's disabled by default.) Because if so, then the behavior your described is expected.

**Comment by mqudsi** [comment]
Ah, I have `literal_separator` set because I only want to match files in cwd.
I guess that explains it.
