### ISSUE TITLE
Don't warn for broken ignore syntax

### ISSUE THREAD

**Issue by bluss** [BurntSushi/ripgrep#646]
Example case:

```
$ rg SliceRef
<some directory>/.gitignore: line 2: error parsing glob '**.DS_Store': invalid use of **; must be one path component
```

My idea here is that I'm interested in help searching through a hairy mess of files. The syntax errors are not interesting, in that case, it's from some checked-out code that I don't know anything about anymore.

The errant line seems to be this:

```
**.DS_Store
```

* Ripgrep version: 0.6.0 from crates.io

**Comment by BurntSushi** [comment]
There's a little discussion on this in #373, where I in particular suggest the use of `--no-messages`.

I don't agree with completely suppressing gitignore errors, since I think they are useful for diagnosing `.gitignore` problems. Notably, `git` doesn't report any errors, it just silently ignores bad patterns and I've seen more than a few cases where ripgrep made folks realize that their `.gitignore` files were actually wrong!

**Comment by FSMaxB** [comment]
Quick workaround: `rg SliceRef 2> /dev/null`

The error messages are written to `stderr`, so you can just suppress them like that.

**Comment by bluss** [comment]
--no-messages is a good existing workaround too. I'll just research what else I might be missing with it.

**Comment by BurntSushi** [comment]
@bluss Have you amassed any more thoughts on this topic? Every time I look at this issue, I wonder how it can be closed, but I am myself torn on it. On the one hand, it surfaces invalid gitignores, on the other hand, it's frustrating if those gitignores aren't your own.
