### ISSUE TITLE
Support for search scopes

### ISSUE THREAD

**Issue by dtrebbien** [BurntSushi/ripgrep#687]
One feature that I think would be very useful for searching source code files is the ability to search within "scopes". For example, there might be a "comments" scope which would restrict the search to single- and multi-line comments. Another possible scope could be "literals" to search within string and numeric literals.

**Comment by BurntSushi** [comment]
This sounds cool, but requires language aware parsing support. Even if I accepted this as something I would want in ripgrep, it will be years before it ever happens. So I'm just going to close this.

There are other issues tracking similar features that have a more restricted scope, and even then, the scope still feels large. I'm on mobile, otherwise I'd dig them up.

**Comment by chris-morgan** [comment]
In what I was doing today, this occurred to me as a *really* useful feature and so I came to request it if no one had before. The mention of similar features made me look through `--help` more closely, and I found `--pre` which can be used in conjunction with another program to approximate this effect. You can search outside of comments if you write a program that filters out the comments, for example (I would recommend replacing them with equivalent whitespace so file positions remain the same). I do not know of any existing programs to achieve *that*, but I haven’t looked, either.
