### ISSUE TITLE
.git/rr-cache

### ISSUE THREAD

**Issue by unphased** [BurntSushi/ripgrep#713]
I'm not sure if it is configuration error on my part, but I understand that rg (by default) filters out things in the git repository hidden folder. 

I do configure rg in my alias with `--hidden` because many of the things i search for ARE in hidden directories and files (such as `.vimrc`, `.config/`), and this for whatever reason leads to the dredging up of `.git/rr-cache/<hash>/{pre,post,this}image` files.

Since I haven't encountered other git repo stuff yet, I'm not sure if this is a bug, I'm curious about what rg *should* do about things in e.g. `.git/` in this situation where `--hidden` is specified.

**Comment by BurntSushi** [comment]
Yeah if you specify `--hidden` then it's supposed to search `.git`. If you don't want ripgrep to search `.git` then put it in an `.ignore` file? e.g., `echo '.git' > .ignore`.

**Comment by unphased** [comment]
Yep, makes sense. I'll be doing that.

**Comment by Wilfred** [comment]
@BurntSushi I hit this today, and I think it's a slight UI gotcha, particularly for users have rerere enabled in git.

`rg foo` doesn't search my `.github/` workflows, but `rg --hidden foo` searches both `.github/` workflows and `.git/`. The `.git/` directory is prone to unwanted matches, particularly `.git/rr-cache` because it has copies of files similar to the ones I'm searching.

It seems strange that this happens even when `--ignore-vcs` is used.

Would you be open to changing this?

**Comment by BurntSushi** [comment]
No, sorry. The way to manipulate this is with ignore files.
