### ISSUE TITLE
Gitter room?

### ISSUE THREAD

**Issue by CrashyBang** [BurntSushi/ripgrep#72]
Would it be possible to setup a [Gitter](https://gitter.im/) room where everyone can chat without having to post an issue?

Cheers.

**Comment by BurntSushi** [comment]
I admit, I find it a little weird for `ripgrep` to have a dedicated chat room. Filing issues seems like it ought to be enough.

With that said, if we do pursue this, I'd rather use IRC.

**Comment by BurntSushi** [comment]
I'm just going to close this. I continue to think a chat room for a tool like this is a bit overkill.

If you want to chat with me, I'm usually on the various IRC/Mozilla Rust channels. `#rust` for Rust specific stuff, but `#rust-offtopic` for `ripgrep` stuff. If `ripgrep` traffic gets too heavy, then we can fork off into our own channel.

**Comment by BurntSushi** [comment]
Since I've been linking people to this issue when they ask for a chat room, I figured I'd add a bit more context and some updates.

Firstly, I no longer hang around on IRC. The only chat rooms I visit these days are the Rust Discord server and the [rust-lang Zulip server](https://rust-lang.zulipchat.com). If you ping me on either of those places, I should see it.

Secondly, the problem with an officially endorsed chat rooms is that they require moderation. I am on the Rust moderation team, but I cannot spend my days sitting in a chat room moderating it.

As a compromise, I reached out to GitHub and specifically requested access to their Discussions beta program. You are now encouraged to post questions---any kind of question---in ripgrep's discussion board: https://github.com/BurntSushi/ripgrep/discussions
