### ISSUE TITLE
Add support for `--passthr{u,ough}` flag

### ISSUE THREAD

**Issue by zx8** [BurntSushi/ripgrep#740]
After reading [this comment](https://news.ycombinator.com/item?id=16097948) on HN, I thought it'd be neat to add support for the `--passthrough` / `--passthru` flag in ripgrep as well.

Thoughts?

**Comment by okdana** [comment]
I was thinking about that myself. I personally think it's easier to do it the way i mentioned in that thread, but it seems like some people are quite passionate about it, and it would be very trivial to add a flag that wraps the pattern in `^|(?:...)`, the way we do with `-w` and `-x`. (At least, that's the method that first comes to mind, because it's easy and i have experience with it.)

**Comment by BurntSushi** [comment]
I'm kind of meh on it, but I don't feel strongly enough to reject it outright.

`ag` spells is `--passthrough` while `ack` spells it `--passthru`. How should ripgrep spell it? o_0 I suppose we could just accept both.

I like @okdana's suggested implementation.

**Comment by okdana** [comment]
If it were me i think i'd make it `--passthru`, with `--passthrough` as like a hidden alias. Can't recall if Clap supports that tho

**Comment by kbknapp** [comment]
> Can't recall if Clap supports that tho

[It does](https://docs.rs/clap/2.29.0/clap/struct.Arg.html#method.alias) :wink:

**Comment by jzinn** [comment]
`--passthru` might be ok for Bill the Cat, but humans should use `--passthrough`.

**Comment by jzinn** [comment]
To respond to the "confused" emoji, "thru" is an informal spelling of "through", and IMO the normal spelling should be preferred.

**Comment by BurntSushi** [comment]
@jzinn both are supported. Ripgrep has no specific goal to be "formal."

Please drop this. It's a waste of time.
