### ISSUE TITLE
ack closed the issues linked in the readme

### ISSUE THREAD

**Issue by ljedrz** [BurntSushi/ripgrep#803]
`ack` seems to have closed [the](https://github.com/beyondgrep/ack2/issues/445) [bugs](https://github.com/beyondgrep/ack2/issues/14) that are linked in the readme. The other tools have also probably progressed since 2016.

It would probably be a good idea to re-run the benchmark so it's up to date.

**Comment by BurntSushi** [comment]
> ack seems to have closed the bugs that are linked in the readme.

As the issues you've linked state, they are not fixed in ack2 but are fixed in ack3. [ack3 is currently under development.](https://github.com/beyondgrep/ack3) Once ack3 becomes the official stable release, I'll update the benchmark.

> The other tools have also probably progressed since 2016.

Indeed! That's why I periodically update them.

The benchmarks in the README are meant to give a rough glance. If you want more detailed benchmarks, then [see my blog post](http://blog.burntsushi.net/ripgrep/), which is also linked in the README. The blog post gets updated far less frequently because it is a lot of work. It will happen at my own discretion.
